import "./parish-suggestions";
declare global { interface Window { daum?: { Postcode: new (options:{oncomplete:(data:{zonecode:string;roadAddress:string;jibunAddress:string})=>void})=>{open:()=>void} } } }
type FieldName="managerName"|"name"|"parishCode"|"phone"|"postalCode"|"address"|"addressDetail"|"diocese"|"district"|"jurisdiction"|"officePhone"|"fax"|"homepage";
type Profile={id:number;manager_name:string|null;manager_email:string;name:string;parish_code:string;phone:string;postal_code:string;address:string;address_detail:string;diocese:string;district:string;jurisdiction:string;office_phone:string;fax:string|null;homepage:string|null;approval_status:string;modified_at:string|null};
const loginShell=document.querySelector<HTMLElement>(".shell")!,dashboard=document.querySelector<HTMLElement>("#parish-dashboard")!;
const profileForm=document.querySelector<HTMLFormElement>("#parish-profile-form")!;
const profileFields=Object.fromEntries([...profileForm.querySelectorAll<HTMLInputElement>("input[name]")].map(input=>[input.name,input])) as Record<FieldName,HTMLInputElement>;
const phonePattern=/^(?:02-\d{4}-\d{4}|\d{3}-\d{3,4}-\d{4})$/;
const approvalBadge=document.querySelector<HTMLElement>("#profile-approval-status")!;
function applyApprovedLocks(){const approved=approvalBadge.classList.contains("approved");for(const name of ["name","parishCode"] as const){profileFields[name].readOnly=approved;profileFields[name].classList.toggle("approval-locked",approved);profileFields[name].title=approved?"승인 완료된 성당은 수정할 수 없습니다.":""}}
new MutationObserver(applyApprovedLocks).observe(approvalBadge,{attributes:true,attributeFilter:["class"]});

type ParishNotification={id:number;title:string;message:string;readAt:string|null;createdAt:string;unread:boolean};
function notificationHtml(value:string){const element=document.createElement("div");element.textContent=value;return element.innerHTML}
let parishNotificationTimer=0,parishNotificationInitialized=false,parishLatestNotificationId=0,parishNotifications:ParishNotification[]=[];
function openParishNotifications(){document.querySelector(".parish-notification-modal")?.remove();const layer=document.createElement("div");layer.className="priest-modal parish-notification-modal";layer.innerHTML=`<div class="priest-modal-backdrop" data-parish-notification-close></div><section class="priest-modal-box parish-notification-box"><header><div><p>NOTIFICATIONS</p><h2>알림</h2></div><button data-parish-notification-close type="button">×</button></header><div class="parish-notification-body">${parishNotifications.length?parishNotifications.map(item=>`<article class="${item.unread?"unread":""}"><header><strong>${notificationHtml(item.title)}</strong><b>${item.unread?"읽지 않음":"읽음"}</b></header><p>${notificationHtml(item.message)}</p><footer><time>${new Date(item.createdAt).toLocaleString("ko-KR")}</time>${item.unread?`<button data-parish-notification-read="${item.id}" type="button">읽음</button>`:""}</footer></article>`).join(""):'<div class="parish-notification-empty">도착한 알림이 없습니다.</div>'}</div><footer><button class="secondary" data-parish-notification-close type="button">닫기</button></footer></section>`;document.body.append(layer);layer.querySelectorAll("[data-parish-notification-close]").forEach(button=>button.addEventListener("click",()=>layer.remove()));layer.querySelectorAll<HTMLButtonElement>("[data-parish-notification-read]").forEach(button=>button.onclick=async()=>{button.disabled=true;const response=await fetch(`/api/parish/notifications/${button.dataset.parishNotificationRead}/read`,{method:"POST"});if(!response.ok){button.disabled=false;return}location.reload()})}
function showParishNotificationToast(item:ParishNotification){document.querySelector(".parish-notification-toast")?.remove();const toast=document.createElement("button");toast.className="parish-notification-toast";toast.type="button";toast.innerHTML=`<span>새 알림</span><strong>${notificationHtml(item.title)}</strong><p>${notificationHtml(item.message)}</p>`;document.body.append(toast);toast.onclick=()=>{toast.remove();openParishNotifications()};window.setTimeout(()=>toast.remove(),8000)}
async function pollParishNotifications(announce=true){try{const response=await fetch("/api/parish/notifications"),items=await response.json() as ParishNotification[];if(!response.ok)return;const newest=items[0]?.id??0;if(parishNotificationInitialized&&announce&&newest>parishLatestNotificationId){const arrived=items.find(item=>item.id>parishLatestNotificationId);if(arrived)showParishNotificationToast(arrived)}parishNotifications=items;parishLatestNotificationId=Math.max(parishLatestNotificationId,newest);parishNotificationInitialized=true;const unread=items.filter(item=>item.unread).length,badge=document.querySelector<HTMLElement>("#parish-notification-button b");if(badge){badge.textContent=String(unread);badge.hidden=!unread}}catch(error){console.error(error)}}
function mountParishNotifications(){if(!document.querySelector("#parish-notification-button")){const button=document.createElement("button");button.id="parish-notification-button";button.type="button";button.innerHTML='🔔<b hidden>0</b>';button.title="알림";button.onclick=openParishNotifications;document.querySelector("#parish-logout")!.insertAdjacentElement("beforebegin",button)}window.clearInterval(parishNotificationTimer);void pollParishNotifications(false);parishNotificationTimer=window.setInterval(()=>void pollParishNotifications(),3000)}
function showDashboard(email:string){loginShell.hidden=true;dashboard.hidden=false;document.querySelector("#parish-admin-email")!.textContent=email;startSessionCountdown({logoutUrl:"/api/parish-auth/logout",redirectUrl:"/parish",color:"#1769e0"});mountParishNotifications();loadProfile()}
function showLogin(){stopSessionCountdown();dashboard.hidden=true;loginShell.hidden=false}
async function api<T>(url:string,options?:RequestInit){const response=await fetch(url,{...options,headers:{"Content-Type":"application/json",...(options?.headers??{})}});const data=await response.json() as T&{message?:string;errors?:Record<string,string>};if(response.status===401){showLogin();throw new Error("세션이 만료되었습니다. 다시 로그인해 주세요.")}if(!response.ok)throw Object.assign(new Error(data.message??"요청을 처리하지 못했습니다."),{errors:data.errors});return data}
function errorFor(name:FieldName,text=""){profileFields[name].classList.toggle("invalid",Boolean(text));document.querySelector<HTMLElement>(`[data-profile-error="${name}"]`)!.textContent=text}
function validate(name:FieldName){const value=profileFields[name].value.trim();let error="";if(name==="name"&&(value.length<2||value.length>120))error="성당 이름은 2~120자로 입력해 주세요.";if(name==="parishCode"&&!/^[A-Za-z0-9_-]{2,40}$/.test(value))error="영문, 숫자, _, -를 사용해 2~40자로 입력해 주세요.";if((name==="phone"||name==="officePhone")&&!phonePattern.test(value))error="전화번호 형식을 확인해 주세요.";if(name==="fax"&&value&&!phonePattern.test(value))error="팩스 형식을 확인해 주세요.";if(name==="postalCode"&&!/^\d{5}$/.test(value))error="주소 검색으로 우편번호를 선택해 주세요.";if(["address","addressDetail","diocese","district","jurisdiction"].includes(name)&&!value)error="필수 입력 항목입니다.";if(name==="homepage"&&value){try{const u=new URL(value);if(!/^https?:$/.test(u.protocol))throw new Error()}catch{error="올바른 홈페이지 URL을 입력해 주세요."}}errorFor(name,error);return!error}
function formatPhone(input:HTMLInputElement){const raw=input.value.replace(/\D/g,"");const seoul=raw.startsWith("02");const digits=raw.slice(0,seoul?10:11);input.value=seoul?[digits.slice(0,2),digits.slice(2,6),digits.slice(6,10)].filter(Boolean).join("-"):digits.length<=10?[digits.slice(0,3),digits.slice(3,6),digits.slice(6,10)].filter(Boolean).join("-"):[digits.slice(0,3),digits.slice(3,7),digits.slice(7,11)].filter(Boolean).join("-")}
for(const [name,input] of Object.entries(profileFields) as [FieldName,HTMLInputElement][]){input.addEventListener("input",()=>{if(["phone","officePhone","fax"].includes(name))formatPhone(input);validate(name)});input.addEventListener("blur",()=>validate(name))}
profileFields.managerName.addEventListener("input",()=>{const valid=profileFields.managerName.value.trim().length>=2&&profileFields.managerName.value.trim().length<=100;errorFor("managerName",valid?"":"담당자 이름을 2~100자로 입력해 주세요.")});
async function loadProfile(){const p=await api<Profile>("/api/parish/profile");const values:Record<FieldName,string>={managerName:p.manager_name??"",name:p.name,parishCode:p.parish_code,phone:p.phone,postalCode:p.postal_code,address:p.address,addressDetail:p.address_detail,diocese:p.diocese,district:p.district,jurisdiction:p.jurisdiction,officePhone:p.office_phone,fax:p.fax??"",homepage:p.homepage??""};document.querySelector<HTMLInputElement>("#profile-managerEmail")!.value=p.manager_email;for(const [name,value] of Object.entries(values) as [FieldName,string][])profileFields[name].value=value;document.querySelector("#parish-admin-name")!.textContent=p.name;const status=document.querySelector<HTMLElement>("#profile-approval-status")!;status.className=`profile-status ${p.approval_status??"pending"}`;status.textContent=({pending:"승인 대기",approved:"승인 완료",cancelled:"취소"} as Record<string,string>)[p.approval_status]??"승인 대기";document.querySelector("#profile-modified-at")!.textContent=p.modified_at?`최근 수정: ${new Intl.DateTimeFormat("ko-KR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(p.modified_at))}`:""}
document.querySelector("#profile-find-address")!.addEventListener("click",()=>{if(!window.daum?.Postcode)return;new window.daum.Postcode({oncomplete(data){profileFields.postalCode.value=data.zonecode;profileFields.address.value=data.roadAddress||data.jibunAddress;errorFor("postalCode");errorFor("address");profileFields.addressDetail.focus()}}).open()});
profileForm.addEventListener("submit",async event=>{event.preventDefault();if(!(Object.keys(profileFields) as FieldName[]).map(validate).every(Boolean))return document.querySelector<HTMLInputElement>("#parish-profile-form input.invalid")?.focus();const payload=Object.fromEntries((Object.entries(profileFields) as [FieldName,HTMLInputElement][]).map(([name,input])=>[name,input.value.trim()]));try{const data=await api<{message:string}>("/api/parish/profile",{method:"PATCH",body:JSON.stringify(payload)});window.dispatchEvent(new CustomEvent("parish:notice",{detail:data.message}));await loadProfile()}catch(reason){const failure=reason as Error&{errors?:Record<string,string>};if(failure.errors)for(const [name,text]of Object.entries(failure.errors))errorFor(name as FieldName,text);window.dispatchEvent(new CustomEvent("parish:notice",{detail:failure.message}))}});
document.querySelector("#parish-logout")!.addEventListener("click",async()=>{try{await api("/api/parish-auth/logout",{method:"POST"})}finally{showLogin()}});
window.addEventListener("parish:authenticated",(event)=>showDashboard((event as CustomEvent<{email:string}>).detail.email));
window.addEventListener("parish:notice",event=>{const alert=document.querySelector<HTMLElement>("#parish-login-alert")!,title=document.querySelector("#parish-alert-title")!,message=document.querySelector("#parish-alert-message")!,confirm=document.querySelector<HTMLButtonElement>("#parish-alert-confirm")!;title.textContent="알림";message.textContent=(event as CustomEvent<string>).detail;alert.hidden=false;confirm.onclick=()=>{alert.hidden=true;document.body.classList.remove("modal-open")}});
api<{email:string}>("/api/parish-auth/me").then(data=>showDashboard(data.email)).catch(()=>showLogin());
function reloadGridData(table:HTMLTableElement,sourceTrigger:HTMLButtonElement|null,button:HTMLButtonElement){button.disabled=true;button.classList.add("loading");const finish=()=>{window.setTimeout(()=>{button.disabled=false;button.classList.remove("loading")},500)},modal=table.closest<HTMLElement>(".priest-modal");if(modal&&sourceTrigger&&document.contains(sourceTrigger)){sourceTrigger.click();finish();return}if(table.closest("#parishioner-grid")){document.querySelector<HTMLButtonElement>("#parishioner-search-button")?.click();finish();return}if(table.closest("#parish-group-grid")){document.querySelector<HTMLButtonElement>('[data-member-view="groups"]')?.click();finish();return}const scope=table.closest<HTMLElement>("section,article,main")??dashboard,queryButton=scope.querySelector<HTMLButtonElement>('button[id*="search"],button[id*="query"],button[data-search],button[data-query]');if(queryButton&&!queryButton.classList.contains("grid-reload-button")){queryButton.click();finish();return}const active=[...document.querySelectorAll<HTMLButtonElement>('#parish-dashboard button.active[data-member-view],#parish-dashboard button.active[data-sharing-view],#parish-dashboard button.active[data-main-view],#parish-dashboard .parish-subnav button.active')].filter(item=>!item.closest("[hidden]"));if(active.length){active[active.length-1]!.click();finish();return}table.dispatchEvent(new CustomEvent("parish:grid-reload",{bubbles:true,detail:{table}}));finish()}
function mountGridReloadButtons(){document.querySelectorAll<HTMLTableElement>("#parish-dashboard table").forEach(table=>{if(table.dataset.reloadReady)return;table.dataset.reloadReady="true";const wrap=table.closest<HTMLElement>(".parishioner-grid-wrap,.shrine-grid-wrap,.group-members-table-wrap,.mission-applicants-grid,.pilgrims-table-wrap,.priest-grid-wrap,.grid-wrap,.table-wrap")??table.parentElement;if(!wrap)return;const sourceTrigger=document.activeElement instanceof HTMLButtonElement&&!document.activeElement.classList.contains("grid-reload-button")?document.activeElement:null,toolbar=document.createElement("div"),button=document.createElement("button"),scope=table.closest<HTMLElement>(".priest-modal,section,article")??wrap.parentElement;toolbar.className="grid-reload-toolbar grid-reload-inline";button.className="grid-reload-button";button.type="button";button.innerHTML='<span aria-hidden="true">↻</span> Reload';button.title="이 Grid의 최신 데이터 다시 불러오기";button.onclick=()=>reloadGridData(table,sourceTrigger,button);toolbar.append(button);const queryButton=scope?.querySelector<HTMLButtonElement>('button[id*="search"],button[id*="query"],button[data-search],button[data-query]'),queryRow=queryButton?.closest<HTMLElement>("form,.search-row,.search-bar,.query-row,.filter-row,.toolbar")??queryButton?.parentElement;if(queryRow){queryRow.classList.add("has-grid-reload");queryRow.append(toolbar);return}const actionRow=scope?.querySelector<HTMLElement>(":scope>header,.section-header,.list-header,.grid-header");if(actionRow){actionRow.classList.add("has-grid-reload");actionRow.append(toolbar);return}wrap.insertAdjacentElement("beforebegin",toolbar)})}
new MutationObserver(mountGridReloadButtons).observe(dashboard,{childList:true,subtree:true});
mountGridReloadButtons();
export {};
import {startSessionCountdown,stopSessionCountdown} from "./session-countdown";
