import "./parish-schedule";
type Shrine={id:number;diocese:string;name:string;address:string|null;phoneNumbers:string[];websiteUrl:string|null;notes:string[];enabled:boolean;sourceUrl:string;sourceUpdatedDate:string|null;pilgrimCount:number};
type Pilgrim={id:number;name:string;baptismalName:string|null;mobile:string;email:string;visitedAt:string};
type ShrineResponse={items:Shrine[];dioceses:Array<{name:string;count:number}>};
const sharingMainTab=document.querySelector<HTMLButtonElement>('[data-main-view="sharing"]')!;
document.head.insertAdjacentHTML("beforeend",'<style>.parish-settings-tab{margin-left:auto!important;border-left:1px solid var(--line)!important}.parish-settings-tab:before{content:"";position:absolute;left:-13px;top:10px;bottom:10px;width:1px;background:#e6ebf2}.settings-management{min-height:420px}.settings-management>.sharing-view{padding:24px;border:1px solid var(--line);border-radius:12px;background:#fff}@media(max-width:720px){.parish-tabs{overflow-x:auto}.parish-settings-tab{margin-left:24px!important}.parish-settings-tab:before{left:-13px}}</style>');
document.head.insertAdjacentHTML("beforeend",'<style>.schedule-management{min-height:430px;padding:24px;border:1px solid var(--line);border-radius:12px;background:#fff}.schedule-management>header{display:flex;align-items:center;justify-content:space-between;gap:16px;padding-bottom:18px;border-bottom:1px solid var(--line)}.schedule-management h2{margin:0 0 6px}.schedule-management header p{margin:0;color:#748096}.schedule-empty{display:flex;min-height:290px;flex-direction:column;align-items:center;justify-content:center;color:#7b889d;text-align:center}.schedule-empty span{font-size:34px}.schedule-empty strong{margin-top:12px;color:#40506a;font-size:15px}.schedule-empty p{margin:7px 0 0}</style>');
if(!document.querySelector('[data-main-view="prayer"]'))sharingMainTab.insertAdjacentHTML("afterend",'<button class="parish-tab" data-main-view="prayer" type="button"><span>†</span>기도</button>');
const informationMainTab=document.querySelector<HTMLButtonElement>('[data-main-view="information"]')!;
if(!document.querySelector('[data-main-view="settings"]'))informationMainTab.insertAdjacentHTML("afterend",'<button class="parish-tab parish-settings-tab" data-main-view="settings" type="button"><span>⚙</span>설정</button>');
if(!document.querySelector("#prayer-management")){const section=document.createElement("section");section.id="prayer-management";section.className="sharing-management prayer-management";section.hidden=true;section.innerHTML='<section class="sharing-view"><header><div><h2>기도</h2><p>본당 공동체의 기도 활동을 관리합니다.</p></div></header><div class="sharing-empty"><span>†</span><strong>기도 관리 영역</strong><p>기도 관련 기능을 이곳에서 관리할 수 있습니다.</p></div></section>';document.querySelector(".parish-subnav")!.insertAdjacentElement("beforebegin",section)}
if(!document.querySelector("#settings-management")){const section=document.createElement("section");section.id="settings-management";section.className="sharing-management settings-management";section.hidden=true;section.innerHTML='<section class="sharing-view"><header><div><h2>설정</h2><p>성당 관리자 환경과 서비스 설정을 관리합니다.</p></div></header><div class="sharing-empty"><span>⚙</span><strong>설정 관리</strong><p>성당 운영에 필요한 설정 기능을 이곳에서 관리할 수 있습니다.</p></div></section>';document.querySelector(".parish-subnav")!.insertAdjacentElement("beforebegin",section)}
const information=document.querySelector<HTMLElement>("#information-management")!,sharing=document.querySelector<HTMLElement>("#sharing-management")!,prayer=document.querySelector<HTMLElement>("#prayer-management")!,settings=document.querySelector<HTMLElement>("#settings-management")!,sharingSubnav=document.querySelector<HTMLElement>("#sharing-subnav")!,modal=document.querySelector<HTMLElement>("#shrine-editor-modal")!,form=document.querySelector<HTMLFormElement>("#shrine-form")!;
const informationSubnav=information.querySelector<HTMLElement>(".information-subnav")!,shrineCard=information.querySelector<HTMLElement>(".shrine-card")!;informationSubnav.firstElementChild!.setAttribute("data-information-view","shrines");informationSubnav.insertAdjacentHTML("beforeend",'<button class="parish-tag" data-information-view="reviews" type="button">순례후기</button>');shrineCard.insertAdjacentHTML("afterend",'<section id="shrine-review-management" class="shrine-card shrine-review-management" hidden><header class="shrine-header"><div><h2>순례후기 관리</h2><p>본당 신도가 등록한 성지순례 후기와 사진을 확인하고 관리합니다.</p></div></header><div class="shrine-filters"><input id="shrine-review-query" type="search" placeholder="후기 제목, 내용, 성지명, 작성자 검색"><button id="shrine-review-search" class="secondary" type="button">조회</button><button id="shrine-review-reset" class="text-button" type="button">초기화</button></div><div class="shrine-summary"><span id="shrine-review-count"></span></div><div id="shrine-review-list" class="shrine-review-list"></div><div id="shrine-review-empty" class="history-empty" hidden>등록된 순례후기가 없습니다.</div></section>');
let items:Shrine[]=[];let sortState:{key:"diocese"|"name"|"address"|"phone"|"website"|"pilgrimCount"|"enabled";direction:"asc"|"desc"}|null=null;
async function api<T>(url:string,options?:RequestInit){const response=await fetch(url,{...options,headers:{"Content-Type":"application/json",...(options?.headers??{})}});const data=await response.json() as T&{message?:string;errors?:Record<string,string>};if(!response.ok)throw Object.assign(new Error(data.message??"요청을 처리하지 못했습니다."),{errors:data.errors});return data}
function notice(message:string){window.dispatchEvent(new CustomEvent("parish:notice",{detail:message}))}
function escapeHtml(value:string){const div=document.createElement("div");div.textContent=value;return div.innerHTML}
const parishSections=["#parish-profile-form","#priest-management","#history-management","#patron-saint-management","#administrative-guide-management","#video-management","#notice-management"];
const parishSubnavList=document.querySelector<HTMLElement>(".parish-subnav .parish-tag-list")!;
if(!parishSubnavList.querySelector('[data-parish-view="schedule"]'))parishSubnavList.insertAdjacentHTML("beforeend",'<button class="parish-tag" data-parish-view="schedule" type="button" role="tab" aria-selected="false">일정</button>');
if(!document.querySelector("#schedule-management")){const section=document.createElement("section");section.id="schedule-management";section.className="schedule-management";section.hidden=true;section.innerHTML='<header><div><h2>일정 관리</h2><p>성당의 미사, 행사 및 주요 일정을 관리합니다.</p></div><button class="primary" type="button">+ 일정 등록</button></header><div class="schedule-empty"><span>▦</span><strong>등록된 일정이 없습니다.</strong><p>일정 등록 버튼을 눌러 성당 일정을 추가해 주세요.</p></div>';document.querySelector("#parish-profile-form")!.insertAdjacentElement("beforebegin",section)}
const scheduleManagement=document.querySelector<HTMLElement>("#schedule-management")!;
parishSections.push("#schedule-management");
parishSubnavList.querySelector<HTMLButtonElement>('[data-parish-view="schedule"]')!.addEventListener("click",event=>{document.querySelectorAll<HTMLButtonElement>("[data-parish-view]").forEach(tab=>{const active=tab===event.currentTarget;tab.classList.toggle("active",active);tab.setAttribute("aria-selected",String(active))});parishSections.forEach(selector=>document.querySelector<HTMLElement>(selector)!.hidden=selector!=="#schedule-management");document.querySelector<HTMLElement>("#profile-approval-status")!.hidden=true});
const noticePanel=document.querySelector<HTMLElement>("#notice-management")!;
document.querySelectorAll<HTMLButtonElement>("[data-parish-view]").forEach(button=>button.addEventListener("click",()=>{const active=button.dataset.parishView==="notices";noticePanel.hidden=!active;if(active){parishSections.filter(selector=>selector!=="#notice-management").forEach(selector=>document.querySelector<HTMLElement>(selector)!.hidden=true);document.querySelector<HTMLElement>("#profile-approval-status")!.hidden=true}}));
document.querySelectorAll<HTMLButtonElement>("[data-sharing-view]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll<HTMLButtonElement>("[data-sharing-view]").forEach(tab=>{const active=tab===button;tab.classList.toggle("active",active);tab.setAttribute("aria-selected",String(active))});document.querySelectorAll<HTMLElement>("[data-sharing-panel]").forEach(panel=>panel.hidden=panel.dataset.sharingPanel!==button.dataset.sharingView)}));
document.querySelectorAll<HTMLButtonElement>("[data-information-view]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll<HTMLButtonElement>("[data-information-view]").forEach(tab=>tab.classList.toggle("active",tab===button));const reviews=button.dataset.informationView==="reviews";shrineCard.hidden=reviews;document.querySelector<HTMLElement>("#shrine-review-management")!.hidden=!reviews;if(reviews)void loadShrineReviews();else void loadShrines()}));
document.querySelectorAll<HTMLButtonElement>("[data-main-view]").forEach(button=>button.addEventListener("click",async()=>{document.querySelectorAll("[data-main-view]").forEach(tab=>tab.classList.toggle("active",tab===button));const info=button.dataset.mainView==="information",members=button.dataset.mainView==="parishioners",share=button.dataset.mainView==="sharing",pray=button.dataset.mainView==="prayer",setting=button.dataset.mainView==="settings";information.hidden=!info;sharing.hidden=!share;prayer.hidden=!pray;settings.hidden=!setting;sharingSubnav.hidden=!share;document.querySelector<HTMLElement>(".parish-subnav")!.hidden=info||members||share||pray||setting;if(info||share||pray||setting){parishSections.forEach(selector=>document.querySelector<HTMLElement>(selector)!.hidden=true);document.querySelector<HTMLElement>("#profile-approval-status")!.hidden=true;if(info)(document.querySelector<HTMLButtonElement>('[data-information-view="shrines"]'))?.click();if(share)(document.querySelector<HTMLButtonElement>('[data-sharing-view="catacomb"]'))?.click()}else if(!members)(document.querySelector<HTMLButtonElement>('[data-parish-view="basic"]'))?.click()}));
async function loadShrines(){const diocese=(document.querySelector<HTMLSelectElement>("#shrine-diocese")!).value,q=(document.querySelector<HTMLInputElement>("#shrine-query")!).value;try{const result=await api<ShrineResponse>(`/api/parish/shrines?diocese=${encodeURIComponent(diocese)}&q=${encodeURIComponent(q)}`);items=result.items;const select=document.querySelector<HTMLSelectElement>("#shrine-diocese")!,current=select.value;select.replaceChildren(new Option("전체 교구",""),...result.dioceses.map(item=>new Option(`${item.name} (${item.count})`,item.name)));select.value=current;render()}catch(error){notice((error as Error).message)}}
function render(){const list=document.querySelector("#shrine-list")!;list.innerHTML=`<div class="shrine-grid-wrap"><table class="shrine-grid"><thead><tr><th>교구</th><th>성지명</th><th>주소</th><th>전화번호</th><th>홈페이지</th><th>순례자(수)</th><th>사용</th><th>관리</th></tr></thead><tbody>${items.map(item=>{const shortName=Array.from(item.name).slice(0,20).join("")+(Array.from(item.name).length>20?"…":"");const website=item.websiteUrl&&/^https?:\/\//i.test(item.websiteUrl)?`<a href="${escapeHtml(item.websiteUrl)}" target="_blank" rel="noopener noreferrer">바로가기 ↗</a>`:"-";return `<tr class="${item.enabled?"":"is-disabled"}" data-shrine="${item.id}"><td><span class="shrine-diocese-badge">${escapeHtml(item.diocese)}</span></td><td class="shrine-name" title="${escapeHtml(item.name)}">${escapeHtml(shortName)}</td><td title="${escapeHtml(item.address??"")}">${escapeHtml(item.address??"-")}</td><td>${item.phoneNumbers.length?item.phoneNumbers.map(escapeHtml).join("<br>"):"-"}</td><td>${website}</td><td><button class="pilgrim-count" data-action="pilgrims" type="button">${item.pilgrimCount.toLocaleString("ko-KR")}명</button></td><td><label class="shrine-grid-enable"><input type="checkbox" ${item.enabled?"checked":""}><span>${item.enabled?"사용":"미사용"}</span></label></td><td><div class="shrine-grid-actions"><button data-action="edit" type="button">수정</button><button data-action="delete" type="button">삭제</button></div></td></tr>`}).join("")}</tbody></table></div>`;list.querySelectorAll<HTMLElement>("[data-shrine]").forEach(row=>{const item=items.find(value=>value.id===Number(row.dataset.shrine))!;row.querySelector<HTMLInputElement>('input[type="checkbox"]')!.addEventListener("change",event=>saveShrine(item,{enabled:(event.currentTarget as HTMLInputElement).checked}));row.querySelector('[data-action="pilgrims"]')!.addEventListener("click",()=>openPilgrims(item));row.querySelector('[data-action="edit"]')!.addEventListener("click",()=>openEditor(item));row.querySelector('[data-action="delete"]')!.addEventListener("click",()=>removeShrine(item))});document.querySelector("#shrine-count")!.textContent=`검색 결과 ${items.length}개`;document.querySelector<HTMLElement>("#shrine-empty")!.hidden=items.length>0}
const shrineSortKeys=["diocese","name","address","phone","website","pilgrimCount","enabled"] as const;
document.querySelector("#shrine-list")!.addEventListener("click",event=>{const header=(event.target as HTMLElement).closest<HTMLTableCellElement>(".shrine-grid th");if(!header)return;const index=[...header.parentElement!.children].indexOf(header);const key=shrineSortKeys[index];if(!key)return;sortState={key,direction:sortState?.key===key&&sortState.direction==="asc"?"desc":"asc"};const value=(item:Shrine)=>key==="phone"?item.phoneNumbers.join(" "):key==="website"?item.websiteUrl??"":key==="enabled"?Number(item.enabled):item[key]??"";items.sort((a,b)=>{const left=value(a),right=value(b),result=typeof left==="number"&&typeof right==="number"?left-right:String(left).localeCompare(String(right),"ko",{numeric:true});return sortState!.direction==="asc"?result:-result});render();const active=document.querySelectorAll<HTMLTableCellElement>(".shrine-grid th")[index];active?.classList.add(sortState.direction==="asc"?"sort-asc":"sort-desc")});
document.querySelector("#shrine-search")!.addEventListener("click",loadShrines);document.querySelector("#shrine-query")!.addEventListener("keydown",event=>{if((event as KeyboardEvent).key==="Enter")loadShrines()});document.querySelector("#shrine-reset")!.addEventListener("click",()=>{(document.querySelector<HTMLSelectElement>("#shrine-diocese")!).value="";(document.querySelector<HTMLInputElement>("#shrine-query")!).value="";sortState=null;loadShrines()});document.querySelector("#shrine-diocese")!.addEventListener("change",()=>{sortState=null;loadShrines()});
document.querySelector("#shrine-create")!.addEventListener("click",()=>openEditor(null));document.querySelectorAll("[data-shrine-close]").forEach(element=>element.addEventListener("click",closeEditor));
const pilgrimsModal=document.querySelector<HTMLElement>("#shrine-pilgrims-modal")!;
document.querySelectorAll("[data-pilgrims-close]").forEach(element=>element.addEventListener("click",closePilgrims));
async function openPilgrims(shrine:Shrine){pilgrimsModal.hidden=false;document.body.classList.add("modal-open");document.querySelector("#shrine-pilgrims-title")!.textContent=shrine.name;document.querySelector("#shrine-pilgrims-summary")!.textContent="순례자 정보를 불러오는 중입니다.";document.querySelector("#shrine-pilgrims-content")!.innerHTML='<div class="pilgrims-empty">불러오는 중...</div>';try{const result=await api<{items:Pilgrim[]}>(`/api/parish/shrines/${shrine.id}/pilgrims`);document.querySelector("#shrine-pilgrims-summary")!.textContent=`방문 신도 ${result.items.length.toLocaleString("ko-KR")}명`;document.querySelector("#shrine-pilgrims-content")!.innerHTML=result.items.length?`<div class="pilgrims-table-wrap"><table class="pilgrims-table"><thead><tr><th>신도명</th><th>세례명</th><th>연락처</th><th>이메일</th><th>방문일시</th></tr></thead><tbody>${result.items.map(item=>`<tr><td><strong>${escapeHtml(item.name)}</strong></td><td>${escapeHtml(item.baptismalName??"-")}</td><td>${escapeHtml(item.mobile??"-")}</td><td>${escapeHtml(item.email)}</td><td>${new Date(item.visitedAt).toLocaleString("ko-KR")}</td></tr>`).join("")}</tbody></table></div>`:'<div class="pilgrims-empty">이 성지를 방문한 신도가 없습니다.</div>'}catch(error){document.querySelector("#shrine-pilgrims-summary")!.textContent="";document.querySelector("#shrine-pilgrims-content")!.innerHTML=`<div class="pilgrims-empty error">${escapeHtml((error as Error).message)}</div>`}}
function closePilgrims(){pilgrimsModal.hidden=true;document.body.classList.remove("modal-open")}
function field<T extends HTMLInputElement|HTMLTextAreaElement>(id:string){return document.querySelector<T>(id)!}
function openEditor(item:Shrine|null){field<HTMLInputElement>("#shrine-id").value=item?String(item.id):"";field<HTMLInputElement>("#shrine-form-diocese").value=item?.diocese??"";field<HTMLInputElement>("#shrine-form-name").value=item?.name??"";field<HTMLInputElement>("#shrine-form-address").value=item?.address??"";field<HTMLTextAreaElement>("#shrine-form-phones").value=item?.phoneNumbers.join("\n")??"";field<HTMLInputElement>("#shrine-form-website").value=item?.websiteUrl??"";field<HTMLTextAreaElement>("#shrine-form-notes").value=item?.notes.join("\n")??"";field<HTMLInputElement>("#shrine-form-enabled").checked=item?.enabled??true;document.querySelector("#shrine-editor-title")!.textContent=item?"성지 정보 수정":"성지 신규 등록";document.querySelector("#shrine-form-error")!.textContent="";modal.hidden=false;document.body.classList.add("modal-open")}
function closeEditor(){modal.hidden=true;document.body.classList.remove("modal-open")}
function formPayload(){return{diocese:field<HTMLInputElement>("#shrine-form-diocese").value,name:field<HTMLInputElement>("#shrine-form-name").value,address:field<HTMLInputElement>("#shrine-form-address").value,phoneNumbers:field<HTMLTextAreaElement>("#shrine-form-phones").value,websiteUrl:field<HTMLInputElement>("#shrine-form-website").value,notes:field<HTMLTextAreaElement>("#shrine-form-notes").value,enabled:field<HTMLInputElement>("#shrine-form-enabled").checked}}
form.addEventListener("submit",async event=>{event.preventDefault();const id=field<HTMLInputElement>("#shrine-id").value;try{const result=await api<{message:string}>(id?`/api/parish/shrines/${id}`:"/api/parish/shrines",{method:id?"PATCH":"POST",body:JSON.stringify(formPayload())});closeEditor();await loadShrines();notice(result.message)}catch(error){const failure=error as Error&{errors?:Record<string,string>};document.querySelector("#shrine-form-error")!.textContent=failure.errors?Object.values(failure.errors)[0]??failure.message:failure.message}});
async function saveShrine(item:Shrine,change:Partial<Shrine>){try{const result=await api<{message:string}>(`/api/parish/shrines/${item.id}`,{method:"PATCH",body:JSON.stringify({...item,...change})});await loadShrines();notice(result.message)}catch(error){notice((error as Error).message);await loadShrines()}}
async function removeShrine(item:Shrine){if(!window.confirm(`'${item.name}' 정보를 삭제하시겠습니까?`))return;try{const result=await api<{message:string}>(`/api/parish/shrines/${item.id}`,{method:"DELETE"});await loadShrines();notice(result.message)}catch(error){notice((error as Error).message)}}
type ShrineReview={id:number;title:string;reviewText:string|null;tags:string[];createdAt:string;shrineName:string;diocese:string;address:string|null;phoneNumbers:string[];websiteUrl:string|null;notes:string[];authorName:string;baptismalName:string|null;visitedDate:string;imageUrl:string;imageUrls:string[];enabled:boolean};
let shrineReviews:ShrineReview[]=[];
async function loadShrineReviews(){const query=document.querySelector<HTMLInputElement>("#shrine-review-query")!.value.trim();try{shrineReviews=await api<ShrineReview[]>(`/api/parish/shrine-reviews?q=${encodeURIComponent(query)}`);renderShrineReviews()}catch(error){notice((error as Error).message)}}
function renderShrineReviews(){const list=document.querySelector("#shrine-review-list")!;list.innerHTML=shrineReviews.length?`<div class="shrine-review-grid-wrap"><table class="shrine-review-grid"><thead><tr><th>순례지</th><th>후기 제목</th><th>작성자</th><th>순례일</th><th>등록일</th><th>태그</th><th>사진</th><th>노출</th></tr></thead><tbody>${shrineReviews.map(item=>`<tr class="${item.enabled?"":"is-disabled"}"><td><span class="shrine-diocese-badge">${escapeHtml(item.diocese)}</span><button class="shrine-review-shrine" data-review-shrine="${item.id}" type="button">${escapeHtml(item.shrineName)}</button></td><td><button data-review-view="${item.id}" type="button">${escapeHtml(item.title)}</button></td><td>${escapeHtml(item.authorName)}${item.baptismalName?` (${escapeHtml(item.baptismalName)})`:""}</td><td>${escapeHtml(item.visitedDate)}</td><td>${new Date(item.createdAt).toLocaleString("ko-KR")}</td><td>${item.tags.map(tag=>`<span class="shrine-review-tag">#${escapeHtml(tag)}</span>`).join(" ")||"-"}</td><td><button class="shrine-review-photo" data-review-photo="${item.id}" type="button">보기 (${item.imageUrls.length})</button></td><td><label class="shrine-review-enable"><input data-review-enable="${item.id}" type="checkbox" ${item.enabled?"checked":""}><span>${item.enabled?"Enable":"Disable"}</span></label></td></tr>`).join("")}</tbody></table></div>`:"";document.querySelector("#shrine-review-count")!.textContent=`총 ${shrineReviews.length.toLocaleString("ko-KR")}건`;document.querySelector<HTMLElement>("#shrine-review-empty")!.hidden=shrineReviews.length>0;list.querySelectorAll<HTMLButtonElement>("[data-review-view]").forEach(button=>button.onclick=()=>openShrineReview(findReview(button,"reviewView")));list.querySelectorAll<HTMLButtonElement>("[data-review-shrine]").forEach(button=>button.onclick=()=>openReviewShrine(findReview(button,"reviewShrine")));list.querySelectorAll<HTMLButtonElement>("[data-review-photo]").forEach(button=>button.onclick=()=>openReviewPhoto(findReview(button,"reviewPhoto")));list.querySelectorAll<HTMLInputElement>("[data-review-enable]").forEach(input=>input.onchange=()=>setReviewEnabled(findReview(input,"reviewEnable"),input.checked))}
function findReview(element:HTMLElement,key:"reviewView"|"reviewShrine"|"reviewPhoto"|"reviewEnable"){return shrineReviews.find(item=>item.id===Number(element.dataset[key]))!}
function closeReviewModal(layer:HTMLElement,selector:string){layer.querySelectorAll(selector).forEach(element=>element.addEventListener("click",()=>{layer.remove();document.body.classList.remove("modal-open")}))}
function openShrineReview(item:ShrineReview){document.querySelector("#shrine-review-detail-modal")?.remove();document.body.insertAdjacentHTML("beforeend",`<div id="shrine-review-detail-modal" class="priest-modal"><div class="priest-modal-backdrop" data-review-close></div><section class="priest-modal-box shrine-review-detail-box" role="dialog" aria-modal="true"><header><div><p>PILGRIMAGE REVIEW</p><h2>${escapeHtml(item.title)}</h2></div><button data-review-close type="button" aria-label="닫기">×</button></header><div class="shrine-review-detail"><dl><div><dt>순례지</dt><dd>${escapeHtml(item.diocese)} · ${escapeHtml(item.shrineName)}</dd></div><div><dt>작성자</dt><dd>${escapeHtml(item.authorName)}${item.baptismalName?` (${escapeHtml(item.baptismalName)})`:""}</dd></div><div><dt>방문일</dt><dd>${escapeHtml(item.visitedDate)}</dd></div><div><dt>노출 상태</dt><dd>${item.enabled?"Enable":"Disable"}</dd></div><div><dt>태그</dt><dd>${item.tags.map(tag=>`<span>#${escapeHtml(tag)}</span>`).join(" ")||"-"}</dd></div></dl><article>${escapeHtml(item.reviewText??"후기 내용이 없는 이전 등록 자료입니다.")}</article></div><footer><button class="secondary" data-review-close type="button">닫기</button></footer></section></div>`);document.body.classList.add("modal-open");closeReviewModal(document.querySelector<HTMLElement>("#shrine-review-detail-modal")!,"[data-review-close]")}
function openReviewShrine(item:ShrineReview){document.querySelector("#shrine-review-shrine-modal")?.remove();const website=item.websiteUrl&&/^https?:\/\//i.test(item.websiteUrl)?`<a href="${escapeHtml(item.websiteUrl)}" target="_blank" rel="noopener noreferrer">홈페이지 바로가기 ↗</a>`:"-";document.body.insertAdjacentHTML("beforeend",`<div id="shrine-review-shrine-modal" class="priest-modal"><div class="priest-modal-backdrop" data-shrine-info-close></div><section class="priest-modal-box shrine-review-detail-box"><header><div><p>PILGRIMAGE PLACE</p><h2>${escapeHtml(item.shrineName)}</h2></div><button data-shrine-info-close type="button">×</button></header><div class="shrine-review-shrine-info"><dl><div><dt>교구</dt><dd>${escapeHtml(item.diocese)}</dd></div><div><dt>주소</dt><dd>${escapeHtml(item.address??"-")}</dd></div><div><dt>전화번호</dt><dd>${item.phoneNumbers.length?item.phoneNumbers.map(escapeHtml).join("<br>"):"-"}</dd></div><div><dt>홈페이지</dt><dd>${website}</dd></div></dl>${item.notes.length?`<article>${item.notes.map(escapeHtml).join("<br>")}</article>`:""}</div><footer><button class="secondary" data-shrine-info-close type="button">닫기</button></footer></section></div>`);document.body.classList.add("modal-open");closeReviewModal(document.querySelector<HTMLElement>("#shrine-review-shrine-modal")!,"[data-shrine-info-close]")}
function openReviewPhoto(item:ShrineReview){document.querySelector("#shrine-review-photo-modal")?.remove();document.body.insertAdjacentHTML("beforeend",`<div id="shrine-review-photo-modal" class="priest-modal"><div class="priest-modal-backdrop" data-photo-close></div><section class="priest-modal-box shrine-review-photo-box"><header><div><p>UPLOADED PHOTOS · ${item.imageUrls.length}</p><h2>${escapeHtml(item.title)}</h2></div><button data-photo-close type="button">×</button></header><div class="shrine-review-photo-gallery">${item.imageUrls.map((url,index)=>`<figure><img src="${url}" alt="${escapeHtml(item.title)} 사진 ${index+1}"><figcaption>${index+1} / ${item.imageUrls.length}</figcaption></figure>`).join("")}</div><footer><button class="secondary" data-photo-close type="button">닫기</button></footer></section></div>`);document.body.classList.add("modal-open");closeReviewModal(document.querySelector<HTMLElement>("#shrine-review-photo-modal")!,"[data-photo-close]")}
async function setReviewEnabled(item:ShrineReview,enabled:boolean){try{const result=await api<{message:string}>(`/api/parish/shrine-reviews/${item.id}/status`,{method:"PATCH",body:JSON.stringify({enabled})});item.enabled=enabled;renderShrineReviews();notice(result.message)}catch(error){notice((error as Error).message);await loadShrineReviews()}}
document.querySelector("#shrine-review-search")!.addEventListener("click",loadShrineReviews);document.querySelector("#shrine-review-query")!.addEventListener("keydown",event=>{if((event as KeyboardEvent).key==="Enter")void loadShrineReviews()});document.querySelector("#shrine-review-reset")!.addEventListener("click",()=>{document.querySelector<HTMLInputElement>("#shrine-review-query")!.value="";void loadShrineReviews()});
import "./parish-notices";
import "./parish-parishioners";
import "./parish-missions";
export {};
