type PatronContent={contentHtml:string;sourceUrl:string;updatedAt:string|null};
const panel=document.querySelector<HTMLElement>("#patron-saint-management")!,editor=document.querySelector<HTMLElement>("#patron-editor")!,preview=document.querySelector<HTMLElement>("#patron-preview")!;
const allowedTags=new Set(["P","BR","STRONG","B","EM","I","U","UL","OL","LI","H2","H3","BLOCKQUOTE","A"]);
async function api<T>(url:string,options?:RequestInit){const response=await fetch(url,{...options,headers:{"Content-Type":"application/json",...(options?.headers??{})}});const data=await response.json() as T&{message?:string};if(!response.ok)throw new Error(data.message??"요청을 처리하지 못했습니다.");return data}
function notice(message:string){window.dispatchEvent(new CustomEvent("parish:notice",{detail:message}))}
function safeHtml(html:string){const template=document.createElement("template");template.innerHTML=html;const clean=(root:DocumentFragment|Element)=>{[...root.children].forEach(element=>{clean(element);if(!allowedTags.has(element.tagName)){element.replaceWith(...element.childNodes);return}const originalHref=element.getAttribute("href")??"";for(const attribute of [...element.attributes])element.removeAttribute(attribute.name);if(element.tagName==="A"){if(/^https?:\/\//i.test(originalHref)){element.setAttribute("href",originalHref);element.setAttribute("target","_blank");element.setAttribute("rel","noopener noreferrer")}else element.replaceWith(...element.childNodes)}})};clean(template.content);return template.innerHTML}
document.querySelectorAll<HTMLButtonElement>("[data-parish-view]").forEach(button=>button.addEventListener("click",async()=>{const active=button.dataset.parishView==="patron-saint";panel.hidden=!active;if(active){document.querySelector<HTMLElement>("#parish-profile-form")!.hidden=true;document.querySelector<HTMLElement>("#priest-management")!.hidden=true;document.querySelector<HTMLElement>("#history-management")!.hidden=true;document.querySelector<HTMLElement>("#profile-approval-status")!.hidden=true;await loadContent()}}));
async function loadContent(){try{const data=await api<PatronContent>("/api/parish/patron-saint");editor.innerHTML=safeHtml(data.contentHtml);const link=document.querySelector<HTMLAnchorElement>("#patron-source-link")!;link.href=data.sourceUrl;document.querySelector("#patron-updated-at")!.textContent=data.updatedAt?`마지막 저장: ${new Date(data.updatedAt).toLocaleString("ko-KR")}`:"아직 저장된 내용이 없습니다."}catch(error){notice((error as Error).message)}}
document.querySelectorAll<HTMLButtonElement>("[data-rich-command]").forEach(button=>button.addEventListener("mousedown",event=>{event.preventDefault();editor.focus();document.execCommand(button.dataset.richCommand!,false)}));
document.querySelector("#patron-format")!.addEventListener("change",event=>{editor.focus();document.execCommand("formatBlock",false,(event.currentTarget as HTMLSelectElement).value)});
document.querySelector("#patron-add-link")!.addEventListener("mousedown",event=>{event.preventDefault();const url=window.prompt("연결할 주소를 입력해 주세요.","https://");if(!url)return;if(!/^https?:\/\//i.test(url)){notice("http:// 또는 https://로 시작하는 주소를 입력해 주세요.");return}editor.focus();document.execCommand("createLink",false,url)});
document.querySelector("#patron-save")!.addEventListener("click",async()=>{try{const contentHtml=safeHtml(editor.innerHTML);editor.innerHTML=contentHtml;const result=await api<{message:string}>("/api/parish/patron-saint",{method:"PUT",body:JSON.stringify({contentHtml})});notice(result.message);await loadContent()}catch(error){notice((error as Error).message)}});
document.querySelector("#patron-preview-button")!.addEventListener("click",()=>{document.querySelector<HTMLElement>("#patron-preview-content")!.innerHTML=safeHtml(editor.innerHTML);preview.hidden=false;document.body.classList.add("modal-open")});
document.querySelectorAll("[data-patron-preview-close]").forEach(element=>element.addEventListener("click",()=>{preview.hidden=true;document.body.classList.remove("modal-open")}));
export {};
