type HistoryItem={id:number;year:number;month:number;title:string;description:string|null;enabled:boolean};
type HistoryResponse={sortDirection:"asc"|"desc";items:HistoryItem[]};
const panel=document.querySelector<HTMLElement>("#history-management")!,profile=document.querySelector<HTMLElement>("#parish-profile-form")!,clergy=document.querySelector<HTMLElement>("#priest-management")!;
const form=document.querySelector<HTMLFormElement>("#history-form")!,year=document.querySelector<HTMLInputElement>("#history-year")!,month=document.querySelector<HTMLSelectElement>("#history-month")!,title=document.querySelector<HTMLInputElement>("#history-title")!,description=document.querySelector<HTMLTextAreaElement>("#history-description")!,id=document.querySelector<HTMLInputElement>("#history-id")!,errorBox=document.querySelector<HTMLElement>("#history-form-error")!;
let items:HistoryItem[]=[];
for(let value=1;value<=12;value++)month.add(new Option(`${value}월`,String(value)));
async function api<T>(url:string,options?:RequestInit){const response=await fetch(url,{...options,headers:{"Content-Type":"application/json",...(options?.headers??{})}});const data=await response.json() as T&{message?:string;errors?:Record<string,string>};if(!response.ok)throw Object.assign(new Error(data.message??"요청을 처리하지 못했습니다."),{errors:data.errors});return data}
function notice(message:string){window.dispatchEvent(new CustomEvent("parish:notice",{detail:message}))}
function escapeHtml(value:string){const div=document.createElement("div");div.textContent=value;return div.innerHTML}
document.querySelectorAll<HTMLButtonElement>("[data-parish-view]").forEach(button=>button.addEventListener("click",async()=>{const active=button.dataset.parishView==="history";panel.hidden=!active;if(active){profile.hidden=true;clergy.hidden=true;document.querySelector<HTMLElement>("#profile-approval-status")!.hidden=true;await loadHistory()}else panel.hidden=true}));
async function loadHistory(enabledOnly=false){const result=await api<HistoryResponse>(`/api/parish/history${enabledOnly?"?enabled=true":""}`);if(!enabledOnly){items=result.items;(document.querySelector<HTMLSelectElement>("#history-sort")!).value=result.sortDirection;renderAdmin()}return result.items}
function renderAdmin(){const list=document.querySelector("#history-list")!;list.replaceChildren();for(const item of items){const article=document.createElement("article");article.className=`history-item${item.enabled?"":" is-disabled"}`;article.innerHTML=`<time><strong>${item.year}</strong><span>${String(item.month).padStart(2,"0")}월</span></time><div class="history-copy"><h3>${escapeHtml(item.title)}</h3>${item.description?`<p>${escapeHtml(item.description)}</p>`:""}</div><div class="history-item-actions"><label class="history-enable"><input type="checkbox" ${item.enabled?"checked":""}> <span>${item.enabled?"사용":"미사용"}</span></label><button class="history-edit" type="button">수정</button><button class="history-delete" type="button">삭제</button></div>`;const enabled=article.querySelector<HTMLInputElement>(".history-enable input")!;enabled.addEventListener("change",async()=>{await saveItem(item,{enabled:enabled.checked});notice(enabled.checked?"연혁이 활성화되었습니다.":"연혁이 비활성화되었습니다.")});article.querySelector(".history-edit")!.addEventListener("click",()=>startEdit(item));article.querySelector(".history-delete")!.addEventListener("click",()=>removeItem(item));list.append(article)}document.querySelector<HTMLElement>("#history-empty")!.hidden=items.length>0}
function payload(item?:HistoryItem){return{year:Number(year.value),month:Number(month.value),title:title.value.trim(),description:description.value.trim(),enabled:item?.enabled??true}}
form.addEventListener("submit",async event=>{event.preventDefault();errorBox.textContent="";const current=items.find(item=>item.id===Number(id.value));try{const result=await api<{message:string}>(current?`/api/parish/history/${current.id}`:"/api/parish/history",{method:current?"PATCH":"POST",body:JSON.stringify(payload(current))});resetForm();await loadHistory();notice(result.message)}catch(error){const failure=error as Error&{errors?:Record<string,string>};errorBox.textContent=failure.errors?Object.values(failure.errors)[0]??failure.message:failure.message}});
async function saveItem(item:HistoryItem,changes:Partial<HistoryItem>){try{const result=await api<{message:string}>(`/api/parish/history/${item.id}`,{method:"PATCH",body:JSON.stringify({...item,...changes})});await loadHistory();return result}catch(error){notice((error as Error).message);await loadHistory();throw error}}
function startEdit(item:HistoryItem){id.value=String(item.id);year.value=String(item.year);month.value=String(item.month);title.value=item.title;description.value=item.description??"";document.querySelector("#history-submit")!.textContent="저장";document.querySelector<HTMLElement>("#history-cancel-edit")!.hidden=false;form.scrollIntoView({behavior:"smooth",block:"center"})}
function resetForm(){form.reset();id.value="";errorBox.textContent="";document.querySelector("#history-submit")!.textContent="추가";document.querySelector<HTMLElement>("#history-cancel-edit")!.hidden=true}
document.querySelector("#history-cancel-edit")!.addEventListener("click",resetForm);
async function removeItem(item:HistoryItem){if(!window.confirm(`${item.year}년 ${item.month}월 연혁을 삭제하시겠습니까?`))return;try{const result=await api<{message:string}>(`/api/parish/history/${item.id}`,{method:"DELETE"});if(id.value===String(item.id))resetForm();await loadHistory();notice(result.message)}catch(error){notice((error as Error).message)}}
document.querySelector("#history-sort")!.addEventListener("change",async event=>{const sortDirection=(event.currentTarget as HTMLSelectElement).value;try{const result=await api<{message:string}>("/api/parish/history/preferences",{method:"PUT",body:JSON.stringify({sortDirection})});await loadHistory();notice(result.message)}catch(error){notice((error as Error).message)}});
const preview=document.querySelector<HTMLElement>("#history-preview")!;
document.querySelector("#history-view-all")!.addEventListener("click",async()=>{const enabled=await loadHistory(true),list=document.querySelector("#history-preview-list")!;list.innerHTML=enabled.length?enabled.map(item=>`<article><time><strong>${item.year}</strong><span>${String(item.month).padStart(2,"0")}월</span></time><div><h3>${escapeHtml(item.title)}</h3>${item.description?`<p>${escapeHtml(item.description)}</p>`:""}</div></article>`).join(""):'<div class="history-empty">표시할 연혁이 없습니다.</div>';preview.hidden=false;document.body.classList.add("modal-open")});
document.querySelectorAll("[data-history-preview-close]").forEach(element=>element.addEventListener("click",()=>{preview.hidden=true;document.body.classList.remove("modal-open")}));
export {};
