type FieldKey="name"|"baptismalName"|"role"|"appointmentDate"|"affiliation"|"generation"|"birthDate"|"mobile"|"email"|"status"|"incomingDate"|"outgoingDate";
type Alignment="left"|"center"|"right";
type Setting={key:FieldKey;enabled:boolean;required:boolean;searchable:boolean;displayOrder:number;alignment:Alignment;frozen:boolean};
type Revision={id:number;revisionNo:number;active:boolean;createdAt:string};
type Priest={id:number;name:string|null;baptismal_name:string|null;role:string|null;appointment_date:string|null;affiliation:string|null;generation:number|null;birth_date:string|null;mobile:string|null;email:string|null;status:"incoming"|"outgoing";incoming_date:string;outgoing_date:string|null;updated_at:string};
const definitions:Record<FieldKey,{label:string;type:string;property:keyof Priest;options?:string[]}>= {
  name:{label:"이름",type:"text",property:"name"},baptismalName:{label:"세례명",type:"text",property:"baptismal_name"},
  role:{label:"역할",type:"select",property:"role",options:["주임","보좌","은경축","수도회","부주임"]},
  appointmentDate:{label:"부임일",type:"date",property:"appointment_date"},affiliation:{label:"소속",type:"text",property:"affiliation"},
  generation:{label:"세대",type:"number",property:"generation"},birthDate:{label:"생년월일",type:"date",property:"birth_date"},
  mobile:{label:"모바일폰번호",type:"tel",property:"mobile"},email:{label:"이메일",type:"email",property:"email"},
  status:{label:"상태",type:"select",property:"status",options:["전입","전출"]},incomingDate:{label:"전입일",type:"date",property:"incoming_date"},
  outgoingDate:{label:"전출일",type:"date",property:"outgoing_date"},
};
const basicForm=document.querySelector<HTMLElement>("#parish-profile-form")!,panel=document.querySelector<HTMLElement>("#priest-management")!;
const editor=document.querySelector<HTMLElement>("#priest-editor")!,settingsModal=document.querySelector<HTMLElement>("#priest-settings")!;
const fieldsBox=document.querySelector<HTMLElement>("#priest-form-fields")!,form=document.querySelector<HTMLFormElement>("#priest-form")!;
const saveButton=form.querySelector<HTMLButtonElement>('button[type="submit"]')!;
let settings:Setting[]=[];let records:Priest[]=[];let revisions:Revision[]=[];let editing:Priest|null=null;let sortState:{key:FieldKey;direction:"asc"|"desc"}|null=null;let activeClergy:"priests"|"nuns"="priests";
const clergyName=()=>activeClergy==="priests"?"신부":"수녀";const clergyApi=()=>`/api/parish/${activeClergy}`;const isAlwaysRequired=(key:FieldKey)=>key==="baptismalName"||key==="incomingDate";
async function api<T>(url:string,options?:RequestInit){const response=await fetch(url,{...options,headers:{"Content-Type":"application/json",...(options?.headers??{})}});const data=await response.json() as T&{message?:string;errors?:Record<string,string>};if(!response.ok)throw Object.assign(new Error(data.message??"요청을 처리하지 못했습니다."),{errors:data.errors});return data}
function notice(message:string){window.dispatchEvent(new CustomEvent("parish:notice",{detail:message}))}
document.querySelectorAll<HTMLButtonElement>("[data-parish-view]").forEach(button=>button.addEventListener("click",async()=>{document.querySelectorAll("[data-parish-view]").forEach(item=>{item.classList.toggle("active",item===button);item.setAttribute("aria-selected",String(item===button))});const clergy=button.dataset.parishView==="priests"||button.dataset.parishView==="nuns";if(clergy)activeClergy=button.dataset.parishView as "priests"|"nuns";basicForm.hidden=clergy;panel.hidden=!clergy;document.querySelector<HTMLElement>("#profile-approval-status")!.hidden=clergy;if(clergy){document.querySelector("#clergy-management-title")!.textContent=`${clergyName()} 관리`;document.querySelector("#clergy-management-description")!.textContent=`${clergyName()} 등록 정보와 전입·전출 상태를 관리합니다.`;await loadAll()}}));
async function loadAll(){settings=await api<Setting[]>(`${clergyApi()}/settings`);sortState=null;buildSearch();await loadRecords()}
async function loadRecords(){const field=(document.querySelector<HTMLSelectElement>("#priest-search-field")!).value;const q=(document.querySelector<HTMLInputElement>("#priest-search-query")!).value;records=await api<Priest[]>(`${clergyApi()}?field=${encodeURIComponent(field)}&q=${encodeURIComponent(q)}`);renderGrid()}
function buildSearch(){const select=document.querySelector<HTMLSelectElement>("#priest-search-field")!;const current=select.value;select.replaceChildren(new Option("전체 조회조건",""));for(const item of settings.filter(item=>item.searchable))select.add(new Option(definitions[item.key].label,item.key));if([...select.options].some(o=>o.value===current))select.value=current}
function display(key:FieldKey,row:Priest){const value=row[definitions[key].property];if(key==="status")return value==="incoming"?"전입":"전출";if(key==="generation"&&value)return `${value}세대`;if(["appointmentDate","birthDate","incomingDate","outgoingDate"].includes(key)&&value)return String(value).slice(0,10);return value??"-"}
function renderGrid(){const enabled=settings.filter(item=>item.enabled).sort((a,b)=>a.displayOrder-b.displayOrder);const shown=[...records];if(sortState)shown.sort((a,b)=>{const av=a[definitions[sortState!.key].property],bv=b[definitions[sortState!.key].property];const result=av==null?1:bv==null?-1:typeof av==="number"&&typeof bv==="number"?av-bv:String(av).localeCompare(String(bv),"ko",{numeric:true});return sortState!.direction==="asc"?result:-result});const head=document.querySelector("#priest-grid-head")!;head.innerHTML=`<tr>${enabled.map(item=>`<th class="align-${item.alignment}${item.frozen?' is-frozen':''}" data-sort="${item.key}"><button type="button">${definitions[item.key].label}<span>${sortState?.key===item.key?(sortState.direction==="asc"?'▲':'▼'):'↕'}</span></button></th>`).join("")}<th>관리</th></tr>`;head.querySelectorAll<HTMLTableCellElement>("[data-sort]").forEach(th=>th.querySelector("button")!.addEventListener("click",()=>{const key=th.dataset.sort as FieldKey;sortState={key,direction:sortState?.key===key&&sortState.direction==="asc"?"desc":"asc"};renderGrid()}));const body=document.querySelector("#priest-grid-body")!;body.replaceChildren();for(const row of shown){const tr=document.createElement("tr");tr.innerHTML=enabled.map(item=>`<td class="align-${item.alignment}${item.frozen?' is-frozen':''}">${escapeHtml(String(display(item.key,row)))}</td>`).join("")+`<td><button class="priest-edit" type="button">수정</button></td>`;tr.querySelector("button")!.addEventListener("click",()=>openEditor(row));body.append(tr)}applyFrozenColumns();document.querySelector<HTMLElement>("#priest-empty")!.hidden=records.length>0}
function applyFrozenColumns(){const table=document.querySelector<HTMLTableElement>(".priest-grid")!;const header=[...table.querySelectorAll<HTMLTableCellElement>("thead th")];let left=0;header.forEach((th,index)=>{const frozen=th.classList.contains("is-frozen");if(frozen){table.querySelectorAll<HTMLTableCellElement>(`tr > :nth-child(${index+1})`).forEach(cell=>{cell.style.left=`${left}px`;cell.classList.add("is-frozen")});left+=th.getBoundingClientRect().width}})}
function escapeHtml(value:string){const div=document.createElement("div");div.textContent=value;return div.innerHTML}
document.querySelector("#priest-search-button")!.addEventListener("click",()=>loadRecords());document.querySelector("#priest-search-query")!.addEventListener("keydown",event=>{if((event as KeyboardEvent).key==="Enter")loadRecords()});document.querySelector("#priest-search-reset")!.addEventListener("click",()=>{(document.querySelector<HTMLSelectElement>("#priest-search-field")!).value="";(document.querySelector<HTMLInputElement>("#priest-search-query")!).value="";loadRecords()});
document.querySelector("#priest-create")!.addEventListener("click",()=>openEditor(null));
function inputFor(item:Setting,row:Priest|null){const def=definitions[item.key];const value=row?displayRaw(item.key,row):"",required=item.required||isAlwaysRequired(item.key);let control="";if(item.key==="status"){const outgoing=row?.status==="outgoing";control=`<select name="status" ${outgoing?"disabled":""} ${required?"required":""}><option value="incoming">전입</option>${row?'<option value="outgoing">전출</option>':""}</select>`}else if(def.type==="select")control=`<select name="${item.key}" ${required?"required":""}><option value="">선택</option>${def.options!.map(option=>`<option value="${option}" ${value===option?"selected":""}>${option}</option>`).join("")}</select>`;else control=`<input name="${item.key}" type="${def.type}" value="${escapeHtml(String(value))}" ${required?"required":""} ${def.type==="number"?'min="1" step="1"':""} ${item.key==="mobile"?'inputmode="numeric" maxlength="13" placeholder="000-0000-0000"':""}>`;return `<div class="priest-field" data-field="${item.key}"><label>${def.label}${required?' <i>*</i>':""}</label>${control}<p data-priest-error="${item.key}"></p></div>`}
function displayRaw(key:FieldKey,row:Priest){const value=row[definitions[key].property];return ["appointmentDate","birthDate","incomingDate","outgoingDate"].includes(key)&&value?String(value).slice(0,10):value??""}
function openEditor(row:Priest|null){editing=row;document.querySelector("#priest-editor-title")!.textContent=row?"정보 수정":"등록";fieldsBox.innerHTML=settings.filter(item=>item.enabled).map(item=>inputFor(item,row)).join("");if(!row){const status=fieldsBox.querySelector<HTMLSelectElement>('[name="status"]');if(status)status.disabled=true}fieldsBox.oninput=syncSaveButton;fieldsBox.onchange=syncSaveButton;const status=fieldsBox.querySelector<HTMLSelectElement>('[name="status"]');status?.addEventListener("change",toggleOutgoing);bindMobileInput();toggleOutgoing();syncSaveButton();editor.hidden=false;document.body.classList.add("modal-open")}
function bindMobileInput(){const input=fieldsBox.querySelector<HTMLInputElement>('[name="mobile"]');if(!input)return;const error=fieldsBox.querySelector<HTMLElement>('[data-priest-error="mobile"]');const digits=()=>input.value.replace(/\D/g,"").slice(0,11);input.addEventListener("focus",()=>{input.value=digits()});input.addEventListener("input",()=>{input.value=digits();if(error)error.textContent=""});input.addEventListener("blur",()=>{const value=digits();input.value=value.length===11?`${value.slice(0,3)}-${value.slice(3,7)}-${value.slice(7)}`:value;if(error)error.textContent=value&&(!value.startsWith("010")||value.length!==11)?"모바일폰번호는 010으로 시작하는 11자리 번호를 입력해 주세요.":""})}
function toggleOutgoing(){const status=fieldsBox.querySelector<HTMLSelectElement>('[name="status"]')?.value;const outgoing=fieldsBox.querySelector<HTMLElement>('[data-field="outgoingDate"]');if(outgoing)outgoing.hidden=status!=="outgoing";syncSaveButton()}
function syncSaveButton(){const status=fieldsBox.querySelector<HTMLSelectElement>('[name="status"]')?.value;const required=settings.filter(item=>item.enabled&&(item.required||isAlwaysRequired(item.key))&&!(item.key==="outgoingDate"&&status!=="outgoing"));saveButton.disabled=required.some(item=>{const control=fieldsBox.querySelector<HTMLInputElement|HTMLSelectElement>(`[name="${item.key}"]`);return !control||!control.value.trim()||!control.checkValidity()})}
document.querySelectorAll("[data-priest-close]").forEach(el=>el.addEventListener("click",()=>{editor.hidden=true;document.body.classList.remove("modal-open")}));
function collect(){const payload:Record<string,string>={};for(const item of settings.filter(item=>item.enabled)){const input=fieldsBox.querySelector<HTMLInputElement|HTMLSelectElement>(`[name="${item.key}"]`);payload[item.key]=input?.value??(item.key==="status"?(editing?.status??"incoming"):"")}return payload}
form.addEventListener("submit",async event=>{event.preventDefault();if(!await confirmSave())return;try{const payload=collect();const result=await api<{message:string}>(editing?`${clergyApi()}/${editing.id}`:clergyApi(),{method:editing?"PATCH":"POST",body:JSON.stringify(payload)});editor.hidden=true;document.body.classList.remove("modal-open");notice(result.message);await loadRecords()}catch(error){const failure=error as Error&{errors?:Record<string,string>};fieldsBox.querySelectorAll("[data-priest-error]").forEach(el=>el.textContent="");if(failure.errors)for(const[key,message]of Object.entries(failure.errors)){const target=fieldsBox.querySelector(`[data-priest-error="${key}"]`);if(target)target.textContent=message}notice(failure.message)}});
function confirmSave(){return new Promise<boolean>(resolve=>{const box=document.querySelector<HTMLElement>("#priest-confirm")!;box.hidden=false;const close=(answer:boolean)=>{box.hidden=true;yes.onclick=null;no.onclick=null;resolve(answer)};const yes=document.querySelector<HTMLButtonElement>("#priest-confirm-yes")!,no=document.querySelector<HTMLButtonElement>("#priest-confirm-no")!;yes.onclick=()=>close(true);no.onclick=()=>close(false)})}
document.querySelector("#priest-settings-open")!.addEventListener("click",async()=>{document.querySelector("#priest-settings-title")!.textContent=`${clergyName()} 관리항목 설정`;await loadRevisions();renderSettings();settingsModal.hidden=false;document.body.classList.add("modal-open")});document.querySelectorAll("[data-settings-close]").forEach(el=>el.addEventListener("click",()=>{settingsModal.hidden=true;document.body.classList.remove("modal-open")}));
async function loadRevisions(){revisions=await api<Revision[]>(`${clergyApi()}/settings/revisions`);const select=document.querySelector<HTMLSelectElement>("#priest-settings-revision")!;select.replaceChildren(...revisions.map(item=>new Option(`Revision ${item.revisionNo}${item.active?" (적용 중)":""}`,String(item.id),false,item.active)))}
function renderSettings(){const box=document.querySelector("#priest-settings-list")!;box.innerHTML=settings.map(item=>{const fixed=["status","incomingDate","outgoingDate"].includes(item.key);return `<article class="settings-item ${item.enabled?'is-enabled':''}" data-setting="${item.key}"><div class="settings-item-top"><span class="settings-drag" aria-hidden="true">⠿</span><label class="settings-use"><input type="checkbox" data-option="enabled" ${item.enabled?'checked':''} ${fixed?'disabled':''}><strong>${definitions[item.key].label}</strong></label>${fixed?'<em>기본</em>':''}</div><p>신부 ${definitions[item.key].label} 정보</p><div class="settings-options"><label><input type="radio" name="required-${item.key}" data-option="required" ${item.required?'checked':''} ${item.key==="incomingDate"?'disabled':''}> 필수</label><label><input type="radio" name="required-${item.key}" data-option="optional" ${!item.required?'checked':''} ${item.key==="incomingDate"?'disabled':''}> 옵션</label><label class="settings-search"><input type="checkbox" data-option="searchable" ${item.searchable?'checked':''} ${item.key==="outgoingDate"?'disabled':''}> 조회조건</label></div></article>`}).join("");box.querySelectorAll("input").forEach(input=>input.addEventListener("change",()=>{syncSettingCards();renderSettingsPreview()}));syncSettingCards();renderSettingsPreview()}
function syncSettingCards(){document.querySelectorAll<HTMLElement>("[data-setting]").forEach(row=>{const enabled=(row.querySelector('[data-option="enabled"]') as HTMLInputElement).checked;row.classList.toggle("is-enabled",enabled);row.querySelectorAll<HTMLInputElement>('[data-option="required"],[data-option="optional"],[data-option="searchable"]').forEach(input=>input.disabled=!enabled||input.dataset.option==="required"&&row.dataset.setting==="incomingDate"||input.dataset.option==="optional"&&row.dataset.setting==="incomingDate"||input.dataset.option==="searchable"&&row.dataset.setting==="outgoingDate")})}
function draftSettings(){return settings.map(item=>{const row=document.querySelector(`[data-setting="${item.key}"]`)!;return{...item,enabled:(row.querySelector('[data-option="enabled"]') as HTMLInputElement).checked,required:(row.querySelector('[data-option="required"]') as HTMLInputElement).checked,searchable:(row.querySelector('[data-option="searchable"]') as HTMLInputElement).checked}})}
function renderSettingsPreview(){const preview=document.querySelector("#priest-settings-preview")!;preview.innerHTML=draftSettings().filter(item=>item.enabled).map(item=>{const def=definitions[item.key];const required=item.required||item.key==="incomingDate";const control=def.type==="select"?`<select disabled><option>선택</option></select>`:`<input type="${def.type}" ${def.type==="date"?'placeholder="연도-월-일"':''} disabled>`;return `<label><span>${def.label}${required?' <i>*</i>':''}${item.searchable?' <b>조회조건</b>':''}</span>${control}</label>`}).join("")}
document.querySelector("#priest-settings-reload")!.addEventListener("click",async()=>{settings=await api<Setting[]>(`${clergyApi()}/settings`);renderSettings();notice("저장된 설정을 다시 불러왔습니다.")});
document.querySelector("#priest-settings-revision")!.addEventListener("change",async event=>{const select=event.currentTarget as HTMLSelectElement;if(!select.value)return;try{const result=await api<{message:string;settings:Setting[]}>(`${clergyApi()}/settings/revisions/${select.value}/activate`,{method:"POST"});settings=result.settings;await loadRevisions();renderSettings();buildSearch();renderGrid();notice(result.message)}catch(error){notice((error as Error).message)}});
document.querySelector("#priest-settings-save")!.addEventListener("click",async()=>{const updated=draftSettings();try{const result=await api<{message:string;settings:Setting[]}>(`${clergyApi()}/settings`,{method:"PUT",body:JSON.stringify({settings:updated})});settings=result.settings;await loadRevisions();renderSettings();buildSearch();renderGrid();notice(result.message)}catch(error){notice((error as Error).message)}});

const columnsModal=document.querySelector<HTMLElement>("#priest-columns")!;
document.querySelector("#priest-columns-open")!.addEventListener("click",()=>{renderColumns();columnsModal.hidden=false;document.body.classList.add("modal-open")});
document.querySelectorAll("[data-columns-close]").forEach(el=>el.addEventListener("click",()=>{columnsModal.hidden=true;document.body.classList.remove("modal-open")}));
function renderColumns(){const enabled=settings.filter(item=>item.enabled).sort((a,b)=>a.displayOrder-b.displayOrder);const lastFrozen=[...enabled].reverse().find(item=>item.frozen)?.key;const box=document.querySelector("#priest-columns-list")!;box.innerHTML=`<label class="freeze-none"><input type="radio" name="freeze-through" value="" ${lastFrozen?'':'checked'}> 틀 고정 사용 안 함</label>`+enabled.map((item,index)=>`<div class="column-row" data-column="${item.key}"><div class="column-order"><button type="button" data-move="up" ${index===0?'disabled':''}>↑</button><button type="button" data-move="down" ${index===enabled.length-1?'disabled':''}>↓</button></div><strong>${definitions[item.key].label}</strong><div class="align-choice">${(["left","center","right"] as Alignment[]).map(value=>`<label title="${value==='left'?'좌측':value==='center'?'가운데':'우측'} 정렬"><input type="radio" name="align-${item.key}" value="${value}" ${item.alignment===value?'checked':''}><span>${value==='left'?'좌':value==='center'?'중':'우'}</span></label>`).join("")}</div><label class="freeze-choice"><input type="radio" name="freeze-through" value="${item.key}" ${lastFrozen===item.key?'checked':''}><span>여기까지</span></label></div>`).join("");box.querySelectorAll<HTMLButtonElement>("[data-move]").forEach(button=>button.addEventListener("click",()=>{const row=button.closest<HTMLElement>(".column-row")!;const sibling=button.dataset.move==="up"?row.previousElementSibling:row.nextElementSibling;if(sibling?.classList.contains("column-row")){if(button.dataset.move==="up")row.parentElement!.insertBefore(row,sibling);else row.parentElement!.insertBefore(sibling,row);refreshMoveButtons()}}))}
function refreshMoveButtons(){const rows=[...document.querySelectorAll<HTMLButtonElement>("#priest-columns-list .column-row")];rows.forEach((row,index)=>{(row.querySelector('[data-move="up"]') as HTMLButtonElement).disabled=index===0;(row.querySelector('[data-move="down"]') as HTMLButtonElement).disabled=index===rows.length-1})}
document.querySelector("#priest-columns-save")!.addEventListener("click",async()=>{const rows=[...document.querySelectorAll<HTMLElement>("#priest-columns-list .column-row")];const freezeKey=(document.querySelector<HTMLInputElement>('input[name="freeze-through"]:checked')?.value??"") as FieldKey|"";const freezeIndex=rows.findIndex(row=>row.dataset.column===freezeKey);const updated=settings.map(item=>{const index=rows.findIndex(row=>row.dataset.column===item.key);const row=index>=0?rows[index]:null;return{...item,displayOrder:index>=0?index:rows.length+item.displayOrder,alignment:(row?.querySelector<HTMLInputElement>(`input[name="align-${item.key}"]:checked`)?.value??item.alignment) as Alignment,frozen:index>=0&&freezeIndex>=0&&index<=freezeIndex}});try{const result=await api<{message:string;settings:Setting[]}>(`${clergyApi()}/settings`,{method:"PUT",body:JSON.stringify({settings:updated})});settings=result.settings;columnsModal.hidden=true;document.body.classList.remove("modal-open");buildSearch();renderGrid();notice("컬럼 조정 설정이 저장되었습니다.")}catch(error){notice((error as Error).message)}});
export {};
