type Attachment={slot:number;name:string;type:string};
type Notice={id:number;title:string;content:string;pinned:boolean;popupEnabled:boolean;popupFrom:string|null;popupTo:string|null;attachments:Attachment[];createdAt:string;updatedAt:string};
type Upload={name:string;type:string;data?:string;existingSlot?:number};
const panel=document.querySelector<HTMLElement>("#notice-management")!,modal=document.querySelector<HTMLElement>("#notice-editor-modal")!,form=document.querySelector<HTMLFormElement>("#notice-form")!;
let items:Notice[]=[];let retained:Attachment[]=[];
const $=<T extends HTMLElement>(selector:string)=>document.querySelector<T>(selector)!;
function escapeHtml(value:string){const div=document.createElement("div");div.textContent=value;return div.innerHTML}
async function api<T>(url:string,options?:RequestInit){const response=await fetch(url,{...options,headers:{"Content-Type":"application/json",...(options?.headers??{})}}),data=await response.json() as T&{message?:string;errors?:Record<string,string>};if(!response.ok)throw Object.assign(new Error(data.message??"요청을 처리하지 못했습니다."),{errors:data.errors});return data}
function notice(message:string){window.dispatchEvent(new CustomEvent("parish:notice",{detail:message}))}
document.querySelectorAll<HTMLButtonElement>("[data-parish-view]").forEach(button=>button.addEventListener("click",async()=>{if(button.dataset.parishView==="notices")await load()}));
async function load(){try{items=await api<Notice[]>("/api/parish/notices");render()}catch(error){notice((error as Error).message)}}
function render(){const list=$("#notice-list");list.innerHTML=items.map(item=>`<article class="notice-row"><div class="notice-flags">${item.pinned?'<span class="is-pinned">상단 고정</span>':""}${item.popupEnabled?'<span class="is-popup">팝업</span>':""}</div><div class="notice-copy"><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.content)}</p><small>${new Date(item.updatedAt).toLocaleString("ko-KR")} · 첨부 ${item.attachments.length}개${item.popupEnabled?` · ${item.popupFrom} ~ ${item.popupTo}`:""}</small></div><div class="notice-actions"><button data-edit="${item.id}" type="button">수정</button><button data-delete="${item.id}" type="button">삭제</button></div></article>`).join("");list.querySelectorAll<HTMLButtonElement>("[data-edit]").forEach(button=>button.onclick=()=>open(items.find(item=>item.id===Number(button.dataset.edit))!));list.querySelectorAll<HTMLButtonElement>("[data-delete]").forEach(button=>button.onclick=()=>remove(Number(button.dataset.delete)));$("#notice-count").textContent=`총 ${items.length}개`;$("#notice-empty").hidden=items.length>0}
function renderRetained(){$("#notice-files-current").innerHTML=retained.map(file=>`<span>${escapeHtml(file.name)} <button type="button" data-remove-file="${file.slot}">×</button></span>`).join("");document.querySelectorAll<HTMLButtonElement>("[data-remove-file]").forEach(button=>button.onclick=()=>{retained=retained.filter(file=>file.slot!==Number(button.dataset.removeFile));renderRetained()})}
function open(item:Notice|null){form.reset();$("#notice-id").setAttribute("value",item?String(item.id):"");(<HTMLInputElement>$("#notice-title")).value=item?.title??"";(<HTMLTextAreaElement>$("#notice-content")).value=item?.content??"";(<HTMLInputElement>$("#notice-pinned")).checked=item?.pinned??false;(<HTMLInputElement>$("#notice-popup")).checked=item?.popupEnabled??false;(<HTMLInputElement>$("#notice-popup-from")).value=item?.popupFrom?.slice(0,10)??"";(<HTMLInputElement>$("#notice-popup-to")).value=item?.popupTo?.slice(0,10)??"";retained=[...(item?.attachments??[])];renderRetained();togglePeriod();$("#notice-editor-title").textContent=item?"공지사항 수정":"공지사항 등록";$("#notice-form-error").textContent="";modal.hidden=false;document.body.classList.add("modal-open")}
function close(){modal.hidden=true;document.body.classList.remove("modal-open")}
function togglePeriod(){const enabled=(<HTMLInputElement>$("#notice-popup")).checked;$("#notice-popup-period").hidden=!enabled;(<HTMLInputElement>$("#notice-popup-from")).required=enabled;(<HTMLInputElement>$("#notice-popup-to")).required=enabled}
async function fileUpload(file:File):Promise<Upload>{if(file.size>5*1024*1024)throw new Error(`${file.name}: 파일당 최대 용량은 5MB입니다.`);const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]??"");reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)});return{name:file.name,type:file.type||"application/octet-stream",data}}
form.addEventListener("submit",async event=>{event.preventDefault();const selected=[...(<HTMLInputElement>$("#notice-files")).files??[]];if(retained.length+selected.length>2){$("#notice-form-error").textContent="첨부파일은 최대 2개까지 등록할 수 있습니다.";return}try{const uploads:Upload[]=[...retained.map(file=>({name:file.name,type:file.type,existingSlot:file.slot})),...await Promise.all(selected.map(fileUpload))];const id=(<HTMLInputElement>$("#notice-id")).value,payload={title:(<HTMLInputElement>$("#notice-title")).value,content:(<HTMLTextAreaElement>$("#notice-content")).value,pinned:(<HTMLInputElement>$("#notice-pinned")).checked,popupEnabled:(<HTMLInputElement>$("#notice-popup")).checked,popupFrom:(<HTMLInputElement>$("#notice-popup-from")).value,popupTo:(<HTMLInputElement>$("#notice-popup-to")).value,attachments:uploads};const result=await api<{message:string}>(id?`/api/parish/notices/${id}`:"/api/parish/notices",{method:id?"PATCH":"POST",body:JSON.stringify(payload)});close();await load();notice(result.message)}catch(error){const failure=error as Error&{errors?:Record<string,string>};$("#notice-form-error").textContent=failure.errors?Object.values(failure.errors)[0]??failure.message:failure.message}});
async function remove(id:number){if(!confirm("이 공지사항을 삭제하시겠습니까?"))return;try{const result=await api<{message:string}>(`/api/parish/notices/${id}`,{method:"DELETE"});await load();notice(result.message)}catch(error){notice((error as Error).message)}}
$("#notice-create").addEventListener("click",()=>open(null));$("#notice-popup").addEventListener("change",togglePeriod);document.querySelectorAll("[data-notice-close]").forEach(element=>element.addEventListener("click",close));
export {};
