type VideoMetadata={youtubeUrl:string;videoId:string;title:string;authorName:string;thumbnailUrl:string};
type Video=VideoMetadata&{id:number;tags:string[];createdAt:string};
const panel=document.querySelector<HTMLElement>("#video-management")!,form=document.querySelector<HTMLFormElement>("#video-lookup-form")!,urlInput=document.querySelector<HTMLInputElement>("#video-url")!,preview=document.querySelector<HTMLElement>("#video-metadata-preview")!,errorBox=document.querySelector<HTMLElement>("#video-error")!;
let pending:VideoMetadata|null=null;
preview.querySelector(":scope>div")!.insertAdjacentHTML("beforeend",'<label id="video-tags-field" class="video-tags-field" hidden>태그 정보<input id="video-tags" maxlength="1000" placeholder="쉼표(,) 또는 띄어쓰기로 구분"><small>동영상과 관련된 태그를 최대 20개까지 입력할 수 있습니다.</small><span id="video-tag-preview"></span></label>');
const tagsField=document.querySelector<HTMLElement>("#video-tags-field")!,tagsInput=document.querySelector<HTMLInputElement>("#video-tags")!;
tagsInput.addEventListener("input",()=>{const tags=[...new Set(tagsInput.value.split(/[,\s]+/).map(value=>value.replace(/^#/,"").trim()).filter(Boolean))].slice(0,20);document.querySelector("#video-tag-preview")!.innerHTML=tags.map(tag=>`<b>#${escapeHtml(tag)}</b>`).join("")});
async function api<T>(url:string,options?:RequestInit){const response=await fetch(url,{...options,headers:{"Content-Type":"application/json",...(options?.headers??{})}});const data=await response.json() as T&{message?:string};if(!response.ok)throw new Error(data.message??"요청을 처리하지 못했습니다.");return data}
function notice(message:string){window.dispatchEvent(new CustomEvent("parish:notice",{detail:message}))}
function escapeHtml(value:string){const div=document.createElement("div");div.textContent=value;return div.innerHTML}
document.querySelectorAll<HTMLButtonElement>("[data-parish-view]").forEach(button=>button.addEventListener("click",async()=>{const active=button.dataset.parishView==="videos";panel.hidden=!active;if(active){["#parish-profile-form","#priest-management","#history-management","#patron-saint-management","#administrative-guide-management"].forEach(selector=>document.querySelector<HTMLElement>(selector)!.hidden=true);document.querySelector<HTMLElement>("#profile-approval-status")!.hidden=true;await loadVideos()}}));
form.addEventListener("submit",async event=>{event.preventDefault();errorBox.textContent="";preview.hidden=true;tagsField.hidden=true;pending=null;const button=document.querySelector<HTMLButtonElement>("#video-check")!;button.disabled=true;button.textContent="확인 중...";try{pending=await api<VideoMetadata>("/api/parish/videos/metadata",{method:"POST",body:JSON.stringify({url:urlInput.value})});(document.querySelector<HTMLImageElement>("#video-preview-thumbnail")!).src=pending.thumbnailUrl;document.querySelector("#video-preview-title")!.textContent=pending.title;document.querySelector("#video-preview-author")!.textContent=pending.authorName||"채널 정보 없음";const link=document.querySelector<HTMLAnchorElement>("#video-preview-link")!;link.href=pending.youtubeUrl;preview.hidden=false;tagsField.hidden=false;tagsInput.focus()}catch(error){errorBox.textContent=(error as Error).message}finally{button.disabled=false;button.textContent="동영상 확인"}});
document.querySelector("#video-register")!.addEventListener("click",async()=>{if(!pending)return;const button=document.querySelector<HTMLButtonElement>("#video-register")!;button.disabled=true;try{const result=await api<{message:string}>("/api/parish/videos",{method:"POST",body:JSON.stringify({url:pending.youtubeUrl,tags:tagsInput.value})});urlInput.value="";tagsInput.value="";document.querySelector("#video-tag-preview")!.innerHTML="";pending=null;preview.hidden=true;tagsField.hidden=true;await loadVideos();notice(result.message)}catch(error){errorBox.textContent=(error as Error).message}finally{button.disabled=false}});
async function loadVideos(){try{const videos=await api<Video[]>("/api/parish/videos");const list=document.querySelector("#video-list")!;list.innerHTML=videos.map(video=>`<article class="video-card" data-video="${video.id}"><a href="${video.youtubeUrl}" target="_blank" rel="noopener noreferrer"><img src="${video.thumbnailUrl}" alt=""></a><div><h4>${escapeHtml(video.title)}</h4><p>${escapeHtml(video.authorName||"채널 정보 없음")}</p>${video.tags.length?`<div class="video-card-tags">${video.tags.map(tag=>`<b>#${escapeHtml(tag)}</b>`).join("")}</div>`:""}<small>${new Date(video.createdAt).toLocaleDateString("ko-KR")} 등록</small></div><button type="button" aria-label="삭제">삭제</button></article>`).join("");list.querySelectorAll<HTMLButtonElement>("[data-video] button").forEach(button=>button.addEventListener("click",()=>removeVideo(Number(button.closest<HTMLElement>("[data-video]")!.dataset.video))));document.querySelector("#video-count")!.textContent=`총 ${videos.length}개`;document.querySelector<HTMLElement>("#video-empty")!.hidden=videos.length>0}catch(error){notice((error as Error).message)}}
async function removeVideo(id:number){if(!window.confirm("이 동영상을 삭제하시겠습니까?"))return;try{const result=await api<{message:string}>(`/api/parish/videos/${id}`,{method:"DELETE"});await loadVideos();notice(result.message)}catch(error){notice((error as Error).message)}}
export {};
