type CatacombAdminPost={id:number;title:string;content:string;tags:string[];anonymous:boolean;status:"requested"|"approved"|"rejected";rejectionReason:string|null;authorName:string;baptismalName:string|null;createdAt:string};
const esc=(value:unknown)=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!));
let posts:CatacombAdminPost[]=[],filter:"requested"|"approved"="requested";
async function api<T>(url:string,options?:RequestInit){const response=await fetch(url,{...options,headers:{"Content-Type":"application/json",...(options?.headers??{})}}),data=await response.json() as T&{message?:string};if(!response.ok)throw new Error(data.message??"요청을 처리하지 못했습니다.");return data}
function mount(){const panel=document.querySelector<HTMLElement>('[data-sharing-panel="catacomb"]');if(!panel||panel.dataset.adminReady)return;panel.dataset.adminReady="true";panel.innerHTML='<header><div><h2>카타콤 관리</h2><p>신도가 요청한 카타콤을 검토하고 등록된 카타콤을 확인합니다.</p></div><span id="catacomb-admin-count"></span></header><nav class="catacomb-admin-tabs"><button class="active" data-catacomb-status="requested" type="button">등록 요청</button><button data-catacomb-status="approved" type="button">등록 완료</button></nav><div id="catacomb-admin-list"></div><div id="catacomb-admin-empty" class="sharing-empty" hidden><strong>표시할 카타콤이 없습니다.</strong></div>';panel.querySelectorAll<HTMLButtonElement>("[data-catacomb-status]").forEach(button=>button.onclick=()=>{filter=button.dataset.catacombStatus as typeof filter;panel.querySelectorAll("[data-catacomb-status]").forEach(tab=>tab.classList.toggle("active",tab===button));render()})}
function render(){const list=document.querySelector<HTMLElement>("#catacomb-admin-list"),empty=document.querySelector<HTMLElement>("#catacomb-admin-empty"),count=document.querySelector<HTMLElement>("#catacomb-admin-count");if(!list||!empty||!count)return;const items=posts.filter(item=>item.status===filter);count.textContent=`등록 요청 ${posts.filter(item=>item.status==="requested").length}개 · 등록 완료 ${posts.filter(item=>item.status==="approved").length}개`;list.innerHTML=items.map(item=>`<article class="catacomb-admin-card"><header><div><b class="${item.status}">${item.status==="requested"?"등록 요청":"등록 완료"}</b><h3>${esc(item.title)}</h3></div><time>${new Date(item.createdAt).toLocaleString("ko-KR")}</time></header><dl><dt>작성자</dt><dd>${item.anonymous?"익명":`${esc(item.authorName)}${item.baptismalName?` (${esc(item.baptismalName)})`:""}`}</dd><dt>내용</dt><dd>${esc(item.content)}</dd><dt>태그</dt><dd>${item.tags.length?item.tags.map(tag=>`<span>#${esc(tag)}</span>`).join(""):"-"}</dd></dl>${item.status==="requested"?`<footer><button class="secondary" data-catacomb-reject="${item.id}" type="button">반려</button><button class="primary" data-catacomb-approve="${item.id}" type="button">승인</button></footer>`:""}</article>`).join("");empty.hidden=items.length>0;list.querySelectorAll<HTMLButtonElement>("[data-catacomb-approve]").forEach(button=>button.onclick=()=>decide(Number(button.dataset.catacombApprove),"approved"));list.querySelectorAll<HTMLButtonElement>("[data-catacomb-reject]").forEach(button=>button.onclick=()=>reject(Number(button.dataset.catacombReject)))}
async function load(){try{posts=await api<CatacombAdminPost[]>("/api/parish/catacomb/posts");render()}catch(error){window.dispatchEvent(new CustomEvent("parish:notice",{detail:(error as Error).message}))}}
async function decide(id:number,status:"approved"|"rejected",rejectionReason=""){try{const result=await api<{message:string}>(`/api/parish/catacomb/posts/${id}/decision`,{method:"PATCH",body:JSON.stringify({status,rejectionReason})});await load();window.dispatchEvent(new CustomEvent("parish:notice",{detail:result.message}))}catch(error){window.dispatchEvent(new CustomEvent("parish:notice",{detail:(error as Error).message}))}}
function reject(id:number){const reason=window.prompt("반려 사유를 입력해 주세요.")?.trim();if(reason)void decide(id,"rejected",reason)}
document.querySelector<HTMLButtonElement>('[data-sharing-view="catacomb"]')?.addEventListener("click",()=>{mount();void load()});
mount();
document.head.insertAdjacentHTML("beforeend",'<style>.catacomb-admin-tabs{display:flex;gap:7px;margin:16px 0}.catacomb-admin-tabs button{height:36px;padding:0 18px;border:1px solid var(--line);border-radius:18px;background:#fff;font-weight:700}.catacomb-admin-tabs button.active{border-color:var(--green);background:#eaf8f2;color:var(--green)}#catacomb-admin-list{display:grid;gap:12px}.catacomb-admin-card{padding:18px;border:1px solid var(--line);border-radius:12px;background:#fff}.catacomb-admin-card>header{display:flex;justify-content:space-between}.catacomb-admin-card header div{display:flex;align-items:center;gap:9px}.catacomb-admin-card header b{padding:4px 8px;border-radius:10px;font-size:9px}.catacomb-admin-card header b.requested{background:#fff4d8;color:#9b7000}.catacomb-admin-card header b.approved{background:#eaf8f2;color:#16845f}.catacomb-admin-card h3{margin:0}.catacomb-admin-card time{color:var(--muted);font-size:9px}.catacomb-admin-card dl{display:grid;grid-template-columns:70px 1fr;gap:10px;margin:16px 0 0}.catacomb-admin-card dt{color:var(--muted);font-size:10px}.catacomb-admin-card dd{margin:0;line-height:1.65;white-space:pre-wrap}.catacomb-admin-card dd span{display:inline-block;margin-right:5px;padding:3px 7px;border-radius:10px;background:#eef8f4;color:var(--green)}.catacomb-admin-card footer{display:flex;justify-content:flex-end;gap:8px;margin-top:15px;padding-top:13px;border-top:1px solid var(--line)}.catacomb-admin-card footer button{height:36px;padding:0 18px}@media(max-width:700px){.catacomb-admin-card>header{display:block}.catacomb-admin-card time{display:block;margin-top:7px}.catacomb-admin-card dl{grid-template-columns:55px 1fr}}</style>');
