type AdminSuggestion={id:number;title:string;content:string;tags:string[];anonymous:boolean;attachmentName:string|null;status:"requested"|"approved"|"rejected";decisionExplanation:string|null;actionContent:string|null;decidedAt:string|null;createdAt:string;authorName:string;baptismalName:string|null;email:string};
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
async function api<T>(url:string,init?:RequestInit){const response=await fetch(url,{...init,headers:{"Content-Type":"application/json",...(init?.headers??{})}}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"요청을 처리하지 못했습니다.");return data as T}
let suggestions:AdminSuggestion[]=[];
function mount(){const nav=document.querySelector("#sharing-subnav .parish-tag-list"),management=document.querySelector("#sharing-management");if(!nav||!management||nav.querySelector('[data-sharing-view="suggestions"]'))return;nav.insertAdjacentHTML("beforeend",'<button class="parish-tag" data-sharing-view="suggestions" type="button" role="tab" aria-selected="false">제안하기</button>');management.insertAdjacentHTML("beforeend",'<section class="sharing-view suggestion-admin" data-sharing-panel="suggestions" hidden><header><div><h2>제안 관리</h2><p>신도가 제출한 제안을 Grid에서 검토하고 결정 및 조치 내용을 관리합니다.</p></div><span id="suggestion-admin-count"></span></header><div class="suggestion-grid-toolbar"><select id="suggestion-status-filter" aria-label="처리 상태"><option value="">전체 상태</option><option value="requested">결정 대기</option><option value="approved">승인</option><option value="rejected">반려</option></select><input id="suggestion-search" placeholder="제목, 내용, 제안자, 태그 검색"><button id="suggestion-query" class="primary" type="button">조회</button></div><div class="suggestion-grid-wrap"><table class="suggestion-grid"><thead><tr><th>상태</th><th>접수일</th><th>제안자</th><th>제목</th><th>태그</th><th>첨부파일</th><th>결정 설명</th><th>조치 내용</th><th>관리</th></tr></thead><tbody id="suggestion-admin-list"></tbody></table></div><div id="suggestion-admin-empty" class="sharing-empty" hidden><strong>접수된 제안이 없습니다.</strong></div></section>');const button=nav.querySelector<HTMLButtonElement>('[data-sharing-view="suggestions"]')!;button.addEventListener("click",()=>{nav.querySelectorAll<HTMLButtonElement>("[data-sharing-view]").forEach(tab=>{const active=tab===button;tab.classList.toggle("active",active);tab.setAttribute("aria-selected",String(active))});management.querySelectorAll<HTMLElement>("[data-sharing-panel]").forEach(panel=>panel.hidden=panel.dataset.sharingPanel!=="suggestions");void load()});management.querySelector<HTMLButtonElement>("#suggestion-query")!.onclick=render;management.querySelector<HTMLInputElement>("#suggestion-search")!.onkeydown=event=>{if(event.key==="Enter")render()};management.querySelector<HTMLSelectElement>("#suggestion-status-filter")!.onchange=render}
async function load(){const body=document.querySelector<HTMLElement>("#suggestion-admin-list");if(!body)return;try{suggestions=await api<AdminSuggestion[]>("/api/parish/suggestions");document.querySelector<HTMLElement>("#suggestion-admin-count")!.textContent=`총 ${suggestions.length}건`;render()}catch(error){body.innerHTML=`<tr><td colspan="9" class="suggestion-grid-message">${esc((error as Error).message)}</td></tr>`}}
function render(){const body=document.querySelector<HTMLElement>("#suggestion-admin-list");if(!body)return;const status=document.querySelector<HTMLSelectElement>("#suggestion-status-filter")?.value??"",query=(document.querySelector<HTMLInputElement>("#suggestion-search")?.value??"").trim().toLowerCase(),items=suggestions.filter(item=>(!status||item.status===status)&&(!query||[item.title,item.content,item.authorName,item.baptismalName,item.email,...item.tags].some(value=>String(value??"").toLowerCase().includes(query))));body.innerHTML=items.map(item=>`<tr><td><span class="suggestion-grid-status ${item.status}">${item.status==="requested"?"결정 대기":item.status==="approved"?"승인":"반려"}</span></td><td class="suggestion-grid-date">${new Date(item.createdAt).toLocaleDateString("ko-KR")}</td><td><strong>${esc(item.authorName)}${item.baptismalName?` (${esc(item.baptismalName)})`:""}</strong><small>${esc(item.email)}${item.anonymous?" · 익명 제안":""}</small></td><td><button class="suggestion-title-button" data-suggestion-detail="${item.id}" type="button">${esc(item.title)}</button><small>${esc(item.content).slice(0,80)}${item.content.length>80?"…":""}</small></td><td><div class="suggestion-grid-tags">${item.tags.map(tag=>`<span>#${esc(tag)}</span>`).join("")||"-"}</div></td><td>${item.attachmentName?`<a href="/api/parish/suggestions/${item.id}/attachment">📎 보기</a>`:"-"}</td><td class="suggestion-grid-copy">${esc(item.decisionExplanation)||"-"}</td><td class="suggestion-grid-copy">${esc(item.actionContent)||"-"}</td><td><button class="suggestion-manage-button" data-suggestion-manage="${item.id}" type="button">${item.status==="requested"?"결정":"수정"}</button></td></tr>`).join("");document.querySelector<HTMLElement>("#suggestion-admin-empty")!.hidden=items.length>0;body.closest<HTMLElement>(".suggestion-grid-wrap")!.hidden=items.length===0;body.querySelectorAll<HTMLButtonElement>("[data-suggestion-manage]").forEach(button=>button.onclick=()=>openDecision(Number(button.dataset.suggestionManage)));body.querySelectorAll<HTMLButtonElement>("[data-suggestion-detail]").forEach(button=>button.onclick=()=>openDetail(Number(button.dataset.suggestionDetail)))}
function openDetail(id:number){const item=suggestions.find(value=>value.id===id);if(!item)return;const layer=document.createElement("div");layer.className="priest-modal suggestion-detail-modal";layer.innerHTML=`<div class="priest-modal-backdrop" data-close></div><section class="priest-modal-box"><header><div><p>SUGGESTION</p><h2>${esc(item.title)}</h2></div><button data-close type="button">×</button></header><div class="suggestion-detail-body"><dl><dt>제안자</dt><dd>${esc(item.authorName)}${item.baptismalName?` (${esc(item.baptismalName)})`:""} · ${esc(item.email)}</dd><dt>내용</dt><dd class="pre">${esc(item.content)}</dd><dt>태그</dt><dd>${item.tags.map(tag=>`<span>#${esc(tag)}</span>`).join("")||"-"}</dd></dl></div><footer><button class="secondary" data-close type="button">닫기</button><button class="primary" data-manage type="button">결정 관리</button></footer></section>`;document.body.append(layer);layer.querySelectorAll("[data-close]").forEach(element=>element.addEventListener("click",()=>layer.remove()));layer.querySelector<HTMLButtonElement>("[data-manage]")!.onclick=()=>{layer.remove();openDecision(id)}}
function confirmDecision(status:string){
  return new Promise<boolean>(resolve=>{
    const approved=status==="approved",confirm=document.createElement("div");
    confirm.className="priest-confirm suggestion-decision-confirm";
    confirm.innerHTML=`<div class="priest-modal-backdrop"></div><section role="alertdialog" aria-modal="true" aria-labelledby="suggestion-confirm-title" aria-describedby="suggestion-confirm-message"><div class="confirm-icon">${approved?"✓":"!"}</div><h2 id="suggestion-confirm-title">${approved?"승인":"반려"} 결정을 저장할까요?</h2><p id="suggestion-confirm-message">저장하면 제안자에게 ${approved?"승인":"반려"} 결과와 결정 설명이 알림으로 전달됩니다.</p><div><button class="secondary" data-answer="no" type="button">취소</button><button class="primary" data-answer="yes" type="button">${approved?"승인":"반려"} 저장 및 알림</button></div></section>`;
    document.body.append(confirm);
    const close=(answer:boolean)=>{confirm.remove();resolve(answer)};
    confirm.querySelector<HTMLButtonElement>('[data-answer="no"]')!.onclick=()=>close(false);
    confirm.querySelector<HTMLButtonElement>('[data-answer="yes"]')!.onclick=()=>close(true);
    confirm.querySelector<HTMLButtonElement>('[data-answer="yes"]')!.focus();
  })
}
function openDecision(id:number){
  const item=suggestions.find(value=>value.id===id);if(!item)return;
  const layer=document.createElement("div");layer.className="priest-modal suggestion-decision-modal";
  layer.innerHTML=`<div class="priest-modal-backdrop" data-close></div><section class="priest-modal-box"><header><div><p>SUGGESTION DECISION</p><h2>${esc(item.title)}</h2></div><button data-close type="button">×</button></header><form><div class="suggestion-decision-body"><label>결정<select name="status" required><option value="approved" ${item.status==="approved"?"selected":""}>승인</option><option value="rejected" ${item.status==="rejected"?"selected":""}>반려</option></select></label><label>결정 설명 <i>*</i><textarea name="explanation" rows="5" maxlength="4000" required placeholder="승인 또는 반려 사유를 입력해 주세요.">${esc(item.decisionExplanation)}</textarea></label><label>결정에 따른 조치 내용<textarea name="actionContent" rows="6" maxlength="10000" placeholder="처리 계획 또는 완료된 조치 내용을 입력해 주세요.">${esc(item.actionContent)}</textarea></label><p></p></div><footer><button class="secondary" data-close type="button">취소</button><button class="primary" type="submit">결정 저장 및 알림</button></footer></form></section>`;
  document.body.append(layer);layer.querySelectorAll("[data-close]").forEach(element=>element.addEventListener("click",()=>layer.remove()));
  const form=layer.querySelector<HTMLFormElement>("form")!,status=form.querySelector<HTMLSelectElement>('[name="status"]')!,explanation=form.querySelector<HTMLTextAreaElement>('[name="explanation"]')!,action=form.querySelector<HTMLTextAreaElement>('[name="actionContent"]')!,error=form.querySelector<HTMLElement>(".suggestion-decision-body>p")!,submit=form.querySelector<HTMLButtonElement>('button[type="submit"]')!;
  const syncSubmit=()=>{submit.disabled=!status.value||!explanation.value.trim()||!explanation.checkValidity()};
  form.addEventListener("input",syncSubmit);form.addEventListener("change",syncSubmit);syncSubmit();
  form.onsubmit=async event=>{event.preventDefault();if(submit.disabled)return;if(!await confirmDecision(status.value))return;error.textContent="";submit.disabled=true;try{await api(`/api/parish/suggestions/${id}/decision`,{method:"PATCH",body:JSON.stringify({status:status.value,explanation:explanation.value,actionContent:action.value})});layer.remove();await load()}catch(reason){error.textContent=(reason as Error).message;syncSubmit()}}
}
document.addEventListener("click",event=>{const button=(event.target as HTMLElement).closest<HTMLElement>("[data-suggestion-detail],[data-suggestion-manage]");const id=Number(button?.dataset.suggestionDetail??button?.dataset.suggestionManage);if(id)void api(`/api/parish/suggestions/${id}/read`,{method:"POST"})},true);
new MutationObserver(mount).observe(document.body,{childList:true,subtree:true});queueMicrotask(mount);
document.head.insertAdjacentHTML("beforeend",'<style>.suggestion-admin>header{display:flex;justify-content:space-between}.suggestion-grid-toolbar{display:grid;grid-template-columns:150px minmax(260px,1fr) 84px;gap:8px;margin:15px 0}.suggestion-grid-toolbar select,.suggestion-grid-toolbar input{height:40px;padding:0 11px;border:1px solid var(--line);border-radius:8px;background:#fff}.suggestion-grid-wrap{overflow:auto;border:1px solid var(--line);border-radius:11px;background:#fff}.suggestion-grid{width:100%;min-width:1250px;border-collapse:collapse}.suggestion-grid th,.suggestion-grid td{padding:11px 10px;border-bottom:1px solid var(--line);font-size:10px;text-align:left;vertical-align:top}.suggestion-grid th{position:sticky;top:0;z-index:1;background:#f4f8f6;color:#66776f;white-space:nowrap}.suggestion-grid td small{display:block;margin-top:5px;color:var(--muted);line-height:1.5}.suggestion-grid-status{display:inline-block;padding:4px 8px;border-radius:11px;background:#fff3d6;color:#966b00;white-space:nowrap}.suggestion-grid-status.approved{background:#e9f8f2;color:#16845f}.suggestion-grid-status.rejected{background:#fff0f1;color:#c43b48}.suggestion-grid-date{white-space:nowrap}.suggestion-title-button{padding:0;border:0;background:none;color:#174f3e;font-weight:800;text-align:left;cursor:pointer}.suggestion-grid-tags{display:flex;max-width:150px;flex-wrap:wrap;gap:4px}.suggestion-grid-tags span,.suggestion-detail-body dd span{padding:3px 6px;border-radius:9px;background:var(--soft);color:var(--green);white-space:nowrap}.suggestion-grid-copy{max-width:180px;line-height:1.55;white-space:pre-wrap}.suggestion-manage-button{padding:7px 11px;border:1px solid var(--green);border-radius:7px;background:#fff;color:var(--green);font-weight:700;cursor:pointer;white-space:nowrap}.suggestion-detail-modal .priest-modal-box,.suggestion-decision-modal .priest-modal-box{width:min(94vw,720px)}.suggestion-detail-body,.suggestion-decision-body{padding:22px;overflow-y:auto}.suggestion-detail-body dl{display:grid;grid-template-columns:75px 1fr;gap:13px;margin:0}.suggestion-detail-body dt{color:var(--green);font-weight:800}.suggestion-detail-body dd{margin:0;line-height:1.7}.suggestion-detail-body .pre{white-space:pre-wrap}.suggestion-decision-modal form{min-height:0;overflow:hidden}.suggestion-decision-body{display:grid;gap:12px}.suggestion-decision-body label{font-size:11px;font-weight:700}.suggestion-decision-body select,.suggestion-decision-body textarea{display:block;width:100%;margin-top:6px;padding:10px;border:1px solid var(--line);border-radius:8px;background:#fff}.suggestion-decision-body p{margin:0;color:#d94350}.suggestion-detail-modal footer,.suggestion-decision-modal footer{display:flex;justify-content:center;gap:8px}@media(max-width:700px){.suggestion-grid-toolbar{grid-template-columns:1fr}.suggestion-grid-toolbar button{height:40px}}</style>');
document.head.insertAdjacentHTML("beforeend",'<style>@media(min-width:721px){#sharing-management:not([hidden])>.suggestion-admin:not([hidden]){display:flex;height:calc(100vh - 153px);min-height:430px;flex-direction:column;overflow:visible}.suggestion-admin>header{flex:0 0 auto}.suggestion-admin>.suggestion-grid-toolbar{position:sticky;top:244px;z-index:23;flex:0 0 auto;margin:0;padding:15px 28px;background:#fff;box-shadow:0 5px 12px rgba(29,52,84,.04)}.suggestion-admin>.suggestion-grid-wrap{flex:1;min-height:0;margin:0 28px 22px;border-radius:11px;overscroll-behavior:contain}.suggestion-admin .suggestion-grid thead th{position:sticky;top:0;z-index:3;box-shadow:0 1px #dfe6f0}}</style>');
