type SessionCountdownOptions={logoutUrl:string;extendUrl?:string;redirectUrl:string;color:string};
let options:SessionCountdownOptions|null=null,deadline=0,timer=0,dismissed=false;
const nativeFetch=window.fetch.bind(window);
function removeCountdown(){document.querySelector("#session-countdown-modal")?.remove()}
function resetDeadline(){if(!options)return;deadline=Date.now()+10*60*1000;dismissed=false;removeCountdown()}
window.fetch=(async(input:RequestInfo|URL,init?:RequestInit)=>{const response=await nativeFetch(input,init),url=typeof input==="string"?input:input instanceof URL?input.pathname:input.url;if(options&&url.includes(options.logoutUrl)){stopSessionCountdown()}else if(options&&response.ok&&url.includes("/api/"))resetDeadline();return response}) as typeof window.fetch;
function showCountdown(seconds:number){if(!options||dismissed)return;let layer=document.querySelector<HTMLElement>("#session-countdown-modal");if(!layer){layer=document.createElement("div");layer.id="session-countdown-modal";layer.innerHTML=`<section role="dialog" aria-modal="true" aria-labelledby="session-countdown-title"><div class="session-timeout-icon">⏱</div><h2 id="session-countdown-title">세션 만료 예정</h2><p>로그인 세션이 곧 만료됩니다.</p><strong><span data-session-seconds></span>초</strong><small class="session-error" aria-live="polite"></small><footer><button class="session-extend" type="button">로그인 연장</button><button class="session-logout" type="button">로그아웃</button></footer></section>`;layer.style.setProperty("--session-color",options.color);document.body.append(layer);layer.querySelector<HTMLButtonElement>(".session-extend")!.onclick=()=>void extendSession();layer.querySelector<HTMLButtonElement>(".session-logout")!.onclick=()=>void logoutNow()}layer.querySelector("[data-session-seconds]")!.textContent=String(seconds)}
async function extendSession(){const current=options,layer=document.querySelector<HTMLElement>("#session-countdown-modal");if(!current||!layer)return;const button=layer.querySelector<HTMLButtonElement>(".session-extend")!,error=layer.querySelector<HTMLElement>(".session-error")!,extendUrl=current.extendUrl??current.logoutUrl.replace(/\/logout$/,"/me");button.disabled=true;button.textContent="연장 중...";error.textContent="";try{const response=await nativeFetch(extendUrl,{method:"GET",headers:{"Cache-Control":"no-cache"}});if(response.status===401){stopSessionCountdown();location.href=current.redirectUrl;return}if(!response.ok)throw new Error("로그인 연장에 실패했습니다.");resetDeadline()}catch(reason){button.disabled=false;button.textContent="로그인 연장";error.textContent=(reason as Error).message}}
async function logoutNow(){const current=options;if(!current)return;stopSessionCountdown();try{await nativeFetch(current.logoutUrl,{method:"POST"})}finally{location.href=current.redirectUrl}}
function tick(){if(!options)return;const seconds=Math.max(0,Math.ceil((deadline-Date.now())/1000));if(seconds<=60)showCountdown(seconds);if(seconds===0)void logoutNow()}
export function startSessionCountdown(value:SessionCountdownOptions){options=value;resetDeadline();window.clearInterval(timer);timer=window.setInterval(tick,250);tick()}
export function stopSessionCountdown(){options=null;deadline=0;window.clearInterval(timer);timer=0;removeCountdown()}
const style=document.createElement("style");style.textContent=`#session-countdown-modal{position:fixed;inset:0;z-index:99999;display:grid;place-items:center;padding:20px;background:rgba(8,22,42,.58);backdrop-filter:blur(3px)}#session-countdown-modal section{width:min(100%,390px);padding:32px;border-radius:18px;background:#fff;text-align:center;box-shadow:0 24px 80px rgba(0,0,0,.28)}#session-countdown-modal .session-timeout-icon{display:grid;width:54px;height:54px;margin:0 auto 16px;place-items:center;border-radius:16px;background:color-mix(in srgb,var(--session-color) 12%,white);font-size:25px}#session-countdown-modal h2{margin:0;font-size:21px}#session-countdown-modal p{margin:9px 0;color:#748197;font-size:13px}#session-countdown-modal strong{display:block;margin:18px 0 8px;color:var(--session-color);font-size:27px}#session-countdown-modal .session-error{display:block;min-height:18px;margin-bottom:8px;color:#d94350;font-size:11px}#session-countdown-modal footer{display:grid;grid-template-columns:1fr 1fr;gap:9px}#session-countdown-modal button{height:46px;border:0;border-radius:9px;font:inherit;font-weight:800;cursor:pointer}#session-countdown-modal button:disabled{opacity:.55;cursor:wait}#session-countdown-modal .session-extend{border:1px solid color-mix(in srgb,var(--session-color) 35%,white);background:#fff;color:var(--session-color)}#session-countdown-modal .session-logout{background:var(--session-color);color:#fff}`;document.head.append(style);
