type ApprovalStatus = "pending" | "approved" | "cancelled";
type Parish = { id:number; name:string; parish_code:string|null; phone:string|null; postal_code:string|null; address:string|null; address_detail:string|null; diocese:string|null; district:string|null; jurisdiction:string|null; office_phone:string|null; fax:string|null; homepage:string|null; administrator_emails:string|null; approval_requested_at:string|null; created_at:string; approval_status:ApprovalStatus; cancellation_reason:string|null; modified_by:string|null; modified_at:string|null };
type PreviousSession = { logged_out_at:string; ip_address:string; logout_reason:"manual"|"timeout" } | null;

const loginView=document.querySelector<HTMLElement>("#supervisor-login")!, appView=document.querySelector<HTMLElement>("#supervisor-app")!;
const loginForm=document.querySelector<HTMLFormElement>("#supervisor-login-form")!, loginError=document.querySelector<HTMLElement>("#login-error")!;
const supervisorUsername=document.querySelector<HTMLInputElement>("#supervisor-username")!,supervisorPassword=document.querySelector<HTMLInputElement>("#supervisor-password")!,passwordToggle=document.querySelector<HTMLButtonElement>("#toggle-supervisor-password")!;
const rememberUsername=document.querySelector<HTMLInputElement>("#remember-supervisor-username")!,savedUsernameKey="paxlink.supervisor.login.username";
const table=document.querySelector<HTMLTableSectionElement>("#parish-table")!, empty=document.querySelector<HTMLElement>("#empty-state")!;
const drawer=document.querySelector<HTMLElement>("#detail-drawer")!, drawerContent=document.querySelector<HTMLElement>("#drawer-content")!;
let parishes:Parish[]=[]; let selected:Parish|null=null;
const statusLabel:Record<ApprovalStatus,string>={pending:"승인 대기",approved:"승인 완료",cancelled:"취소"};

passwordToggle.addEventListener("click",()=>{const visible=supervisorPassword.type==="text";supervisorPassword.type=visible?"password":"text";passwordToggle.setAttribute("aria-pressed",String(!visible));passwordToggle.setAttribute("aria-label",visible?"비밀번호 보기":"비밀번호 숨기기")});
try{const savedUsername=localStorage.getItem(savedUsernameKey);if(savedUsername){supervisorUsername.value=savedUsername;rememberUsername.checked=true}}catch{}

function escapeHtml(value:unknown){const div=document.createElement("div");div.textContent=String(value??"");return div.innerHTML}
function date(value:string|null){return value?new Intl.DateTimeFormat("ko-KR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"-"}
async function request<T>(url:string,options?:RequestInit){const response=await fetch(url,{...options,headers:{"Content-Type":"application/json",...(options?.headers??{})}});const data=await response.json() as T&{message?:string};if(response.status===401&&url!=="/api/supervisor/login"){showLogin();throw new Error("로그인이 만료되었습니다.")}if(!response.ok)throw new Error(data.message??"요청을 처리하지 못했습니다.");return data}
function showLogin(){stopSessionCountdown();loginView.hidden=false;appView.hidden=true;drawer.hidden=true}
function showApp(username:string){loginView.hidden=true;appView.hidden=false;document.querySelector("#current-user")!.textContent=username;startSessionCountdown({logoutUrl:"/api/supervisor/logout",redirectUrl:"/supervisor",color:"#1b1b1b"});loadParishes()}

loginForm.addEventListener("submit",async event=>{event.preventDefault();loginError.textContent="";try{const data=await request<{username:string;previousSession:PreviousSession}>("/api/supervisor/login",{method:"POST",body:JSON.stringify({username:supervisorUsername.value,password:supervisorPassword.value})});try{if(rememberUsername.checked)localStorage.setItem(savedUsernameKey,supervisorUsername.value);else localStorage.removeItem(savedUsernameKey)}catch{}showApp(data.username);const previous=data.previousSession;await showAlert(previous?`최근 로그아웃: ${date(previous.logged_out_at)}\n접속 IP: ${previous.ip_address}\n종료 방식: ${previous.logout_reason==="timeout"?"세션 만료":"직접 로그아웃"}`:"이전 로그아웃 기록이 없습니다.")}catch(error){loginError.textContent=(error as Error).message}});
document.querySelector("#logout")!.addEventListener("click",async()=>{await request("/api/supervisor/logout",{method:"POST"});showLogin()});
document.querySelector("#refresh")!.addEventListener("click",()=>loadParishes());

async function loadParishes(){parishes=await request<Parish[]>("/api/supervisor/parishes");renderSummary();renderTable(parishes)}
function renderSummary(){for(const key of ["pending","approved","cancelled"] as ApprovalStatus[])document.querySelector(`#count-${key}`)!.textContent=String(parishes.filter(p=>(p.approval_status??"pending")===key).length);document.querySelector("#count-all")!.textContent=String(parishes.length)}
function renderTable(items:Parish[]){table.replaceChildren();empty.hidden=items.length>0;for(const parish of items){const status=parish.approval_status??"pending";const tr=document.createElement("tr");tr.innerHTML=`<td><strong>${escapeHtml(parish.name)}</strong><small>${escapeHtml(parish.parish_code??"-")}</small></td><td>${escapeHtml([parish.diocese,parish.district,parish.jurisdiction].filter(Boolean).join(" · ")||"-")}</td><td>${escapeHtml(parish.administrator_emails??"-")}</td><td>${date(parish.approval_requested_at??parish.created_at)}</td><td><span class="status ${status}">${statusLabel[status]}</span></td><td>${escapeHtml(parish.modified_by??"-")}</td><td>${date(parish.modified_at)}</td><td><button class="detail-button">상세</button></td>`;tr.querySelector("button")!.addEventListener("click",()=>openDrawer(parish));table.append(tr)}}
document.querySelector<HTMLInputElement>("#parish-filter")!.addEventListener("input",event=>{const q=(event.target as HTMLInputElement).value.trim().toLowerCase();renderTable(parishes.filter(p=>[p.name,p.parish_code,p.administrator_emails].some(v=>v?.toLowerCase().includes(q))))});

function info(label:string,value:unknown,wide=false){return `<div class="info-item ${wide?"wide":""}"><small>${label}</small><strong>${escapeHtml(value||"-")}</strong></div>`}
function openDrawer(parish:Parish){selected=parish;document.querySelector("#drawer-title")!.textContent=parish.name;const status=parish.approval_status??"pending";drawerContent.innerHTML=`<section class="detail-section"><h3>기본 정보</h3><div class="info-grid">${info("성당 ID",parish.parish_code)}${info("담당자",parish.administrator_emails)}${info("대표전화",parish.phone)}${info("행정사무실",parish.office_phone)}${info("팩스",parish.fax)}${info("홈페이지",parish.homepage)}${info("주소",`(${parish.postal_code??"-"}) ${parish.address??""} ${parish.address_detail??""}`,true)}</div></section><section class="detail-section"><h3>관할 구역</h3><div class="info-grid three">${info("교구",parish.diocese)}${info("지구",parish.district)}${info("관할",parish.jurisdiction)}</div></section><section class="detail-section approval-box"><h3>승인 관리</h3><div class="info-grid">${info("승인 요청일",date(parish.approval_requested_at??parish.created_at))}${info("최근 수정",parish.modified_by?`${parish.modified_by} · ${date(parish.modified_at)}`:"-")}</div><label for="approval-status">승인 상태</label><select id="approval-status"><option value="pending" ${status==="pending"?"selected":""}>승인 대기</option><option value="approved" ${status==="approved"?"selected":""}>승인 완료</option><option value="cancelled" ${status==="cancelled"?"selected":""}>취소</option></select><div id="cancel-reason-wrap" ${status!=="cancelled"?"hidden":""}><label for="cancel-reason">취소 사유 <i>*</i></label><textarea id="cancel-reason" maxlength="1000" placeholder="취소 사유를 입력해 주세요.">${escapeHtml(parish.cancellation_reason??"")}</textarea><small class="reason-count">${(parish.cancellation_reason??"").length}/1000</small></div></section>`;const select=drawerContent.querySelector<HTMLSelectElement>("#approval-status")!,wrap=drawerContent.querySelector<HTMLElement>("#cancel-reason-wrap")!;select.addEventListener("change",()=>wrap.hidden=select.value!=="cancelled");drawerContent.querySelector<HTMLTextAreaElement>("#cancel-reason")!.addEventListener("input",e=>{wrap.querySelector(".reason-count")!.textContent=`${(e.target as HTMLTextAreaElement).value.length}/1000`});drawer.hidden=false;document.body.classList.add("drawer-open")}
function closeDrawer(){drawer.hidden=true;document.body.classList.remove("drawer-open");selected=null}document.querySelectorAll("[data-close]").forEach(el=>el.addEventListener("click",closeDrawer));
document.querySelector("#save-approval")!.addEventListener("click",async()=>{if(!selected)return;const status=drawerContent.querySelector<HTMLSelectElement>("#approval-status")!.value as ApprovalStatus;const cancellationReason=drawerContent.querySelector<HTMLTextAreaElement>("#cancel-reason")!.value.trim();if(status==="cancelled"&&!cancellationReason)return showAlert("취소 사유를 입력해 주세요.");try{const result=await request<{message:string}>(`/api/supervisor/parishes/${selected.id}/approval`,{method:"PATCH",body:JSON.stringify({status,cancellationReason})});closeDrawer();await loadParishes();await showAlert(result.message)}catch(error){await showAlert((error as Error).message)}});

const alertBox=document.querySelector<HTMLElement>("#supervisor-alert")!,alertMessage=document.querySelector<HTMLElement>("#supervisor-alert-message")!,alertConfirm=document.querySelector<HTMLButtonElement>("#supervisor-alert-confirm")!;
function showAlert(text:string){return new Promise<void>(resolve=>{alertMessage.textContent=text;alertBox.hidden=false;const close=()=>{alertBox.hidden=true;alertConfirm.removeEventListener("click",close);resolve()};alertConfirm.addEventListener("click",close);alertConfirm.focus()})}

request<{username:string}>("/api/supervisor/me").then(data=>showApp(data.username)).catch(()=>showLogin());
document.head.insertAdjacentHTML("beforeend",'<link rel="icon" type="image/svg+xml" href="/assets/favicon-supervisor.svg">');
import {startSessionCountdown,stopSessionCountdown} from "./session-countdown";
